'use strict';
Object.assign(BA_ART_NAMES,{'hand-palmar-detail':['כף יד — מבט כפי','Hand — palmar view'],'hand-dorsal-detail':['כף יד — מבט גבי','Hand — dorsal view']});
let adCurrent='',adLabels=true,adFocus=true,adChannelView='',adCompareA='SI 2',adCompareB='SI 3',adQuiz=null;
const adOldOpen=openItem,adOldMeridian=meridianDetail,adOldLearn=learnScreen,adOldFlash=flashcard,adOldAbout=aboutScreen;
function adNeighbors(c){const a=D.points.filter(p=>p.m===adPoint(c).m),i=a.findIndex(p=>p.c===c);return [a[i-1]?.c,c,a[i+1]?.c].filter(Boolean);}
function adLandmarks(c){return `<div class="ad-landmarks">${AD.points[c].landmarks.map(l=>`<span>${baEsc(baT(l.he,l.en))}</span>`).join('')}</div>`;}
function adReview(c){const d=AD.points[c];return `<details class="ba-refs"><summary>${baT('מקור ורמת הבדיקה','Source and review status')}</summary><p>${baT('התיאור מבוסס על מאגר המקור שסופק, המפנה ל־WHO 2008, עמ׳ ','The supplied dataset refers to WHO 2008, p. ')}${baEsc(d.page)}.</p><p>${baT('הסימון נבנה ידנית כסכמה יחסית. הוא לא נמדד על גוף ולא עבר אישור קליני. ציוני הדרך תורגמו ונבדקו לשלמות; נדרשת הגהה מקצועית לפני שימוש בהדרכה קלינית.','The marker is an authored relative schematic. It was not measured on a person or clinically approved. Landmark translations were checked for completeness; professional review is still required before clinical teaching use.')}</p>${d.corrected?`<p>${baT('תוקן תיאור אנגלי שהועתק בטעות מ־SI 1. התיאור המעודכן הוא ניסוח ערוך, לאחר השוואה לקטע WHO המאונדקס ברשת.','An English description incorrectly duplicated from SI 1 was corrected. The revised text is an edited summary checked against the indexed WHO excerpt.')}</p>`:''}${['PC 6','LI 4'].includes(c)?`<p>${baT('ההדרכה הייעודית למטופלים הושוותה לדף MSK המקושר. הבדיקה אינה אימות של קואורדינטות התרשים.','The patient guidance was compared with the linked MSK page. This does not validate the diagram coordinates.')}</p>`:''}<a href="https://iris.who.int/bitstream/handle/10665/353407/9789290613831-eng.pdf?sequence=1" target="_blank" rel="noopener noreferrer">WHO · ${baT('מסמך המיקום','Location reference')} ↗</a><a href="review-register.html" target="_blank" rel="noopener">${baT('יומן בדיקת כל הרשומות','Review register for all records')} ↗</a></details>`;}
function adStudy(c){const p=adPoint(c),d=AD.points[c],measure=[...new Set((p.standardLocation.match(/\d+(?:\.\d+)?\s*(?:B-cun|F-cun)/g)||[]))];const dirs=[[/proximal/i,'פרוקסימלי · לכיוון מוצא הגפה','Proximal · toward the limb origin'],[/distal/i,'דיסטלי · הרחק ממוצא הגפה','Distal · away from the limb origin'],[/medial/i,'מדיאלי · לכיוון קו האמצע','Medial · toward the midline'],[/lateral/i,'לטרלי · הרחק מקו האמצע','Lateral · away from the midline'],[/radial/i,'רדיאלי · צד האגודל','Radial · thumb side'],[/ulnar/i,'אולנרי · צד הזרת','Ulnar · little-finger side']].filter(([re])=>re.test(p.standardLocation));
 return `<section class="ba-section ad-study"><span class="ba-tag">${baT('קריאה אנטומית של הרשומה','Reading this record')}</span><h3>${baT('ציוני הדרך של ','Landmarks for ')}<b dir="ltr">${c}</b></h3>${adLandmarks(c)}${dirs.length?`<p>${baT('כיוונים המופיעים בתיאור:','Directions used in this description:')}</p><ul>${dirs.map(x=>`<li>${baT(x[1],x[2])}</li>`).join('')}</ul>`:''}${measure.length?`<p>${baT('מידות יחסיות המופיעות בתיאור:','Relative measures appearing in the description:')} <b dir="ltr">${measure.join(' · ')}</b>. ${baT('קוראים כל מידה יחד עם ציון הדרך והכיוון שאליהם היא מתייחסת. B-cun מחלק מרחקים בין ציוני דרך; F-cun מבוסס על יחסי אצבעות. אין כאן סרגל בסנטימטרים.','Read each measure with its corresponding landmark and direction. B-cun divides landmark distances; F-cun uses finger proportions. This is not a centimetre scale.')}</p>`:''}<details class="ba-refs"><summary>${baT('שאלת זיהוי לפני שממשיכים','A check before moving on')}</summary><p>${baT('איזה ציון דרך מסביר את המיקום של '+c+' ואיך הוא מבדיל אותה מהנקודה הסמוכה?','Which landmark explains '+c+' and distinguishes it from its neighbour?')}</p><p>${baEsc(baT(p.heL,p.referenceExcerpt||p.standardLocation))}</p><button class="chip" data-ad-compare="${c}">${baT('לפתוח השוואה','Open comparison')}</button></details></section>`;
}
function adPointChart(){const d=AD.points[adCurrent];if(!d)return '';return `<div class="ad-tools"><button class="chip" data-ad-labels aria-pressed="${adLabels}">${baT(adLabels?'הסתרת שמות':'הצגת שמות',adLabels?'Hide labels':'Show labels')}</button><button class="chip" data-ad-zoom aria-pressed="${adFocus}">${baT(adFocus?'מבט מלא':'תקריב',adFocus?'Full view':'Close-up')}</button><button class="chip" data-ad-compare="${adCurrent}">${baT('השוואת נקודות','Compare points')}</button></div>${adDiagram(d.view,{codes:adNeighbors(adCurrent),selected:adCurrent,labels:adLabels,focus:adFocus})}<p class="ba-fine">${baT('הטבעת הטורקיז מסמנת את הנקודה שנבחרה. נקודות סמוכות מאותו מסלול מוצגות רק אם הן שייכות לאותו מבט.','The turquoise ring marks the selected point. Adjacent points are shown when they share this view.')}</p>`;}
openItem=function(key){
 if(!key.startsWith('point:'))return adOldOpen(key);
 const c=key.slice(6),p=adPoint(c),d=AD.points[c];if(!p||!d)return;
 adCurrent=c;const art=AD.views[d.view].art||BA.regions[p.region][2],practical=baPractical(p),neighbors=adNeighbors(c).filter(x=>x!==c);
 $('#sheet').innerHTML=`<button class="x" data-close aria-label="${baT('סגירה','Close')}">✕</button><div class="ba-sheet-code" dir="ltr">${c}</div><h2>${baEsc(baName(p))}</h2><p class="ba-sub">${baEsc([p.py,p.zh,baMerName(MER[p.m])].join(' · '))}</p><div id="ad-point-chart">${adPointChart()}</div><div id="as-location">${asPointLocation(p)}</div>${d.variant?`<div class="ad-variant"><b>${baT('במקור מופיעה גם חלופת מיקום','An alternative location is recorded')}</b><p>${baEsc(baT(...d.variant))}</p></div>`:''}${adStudy(c)}<details class="ba-refs ad-context"><summary>${baT('איור אנטומי והקשר אזורי','Anatomical illustration and regional context')}</summary>${baPlate(art,'',true)}<p>${baEsc(BA.regions[p.region][LANG==='he'?3:4])}</p></details>${baSection(baT('שיוכים במסורת','Traditional associations'),baEsc(baT(p.heI||p.heA,p.ind)),baT('מסורת · לא הבטחת השפעה','Tradition · not an effectiveness claim'))}${practical?baSection(baT('הדרכה ייעודית למטופלים','Point-specific patient guidance'),baEsc(practical.text)):''}${p.heC?`<div class="ba-caution">${baEsc(baT(p.heC,baCautionEnglish(p)))}</div>`:''}<div class="ba-neighbors"><b>${baT('להמשיך במסלול','Continue on this channel')}</b><div>${neighbors.map(x=>`<button class="chip" data-open="point:${x}" dir="ltr">${x}</button>`).join('')}<button class="chip" data-ba-channel="${p.m}">${baT('המסלול המלא','Full channel')}</button></div></div><details class="ba-refs"><summary>${baT(p.referenceExcerpt?'קטע מתיאור המקור באנגלית':d.corrected?'תיאור ייחוס ערוך באנגלית':'תיאור המקור באנגלית',p.referenceExcerpt?'English source excerpt':d.corrected?'Edited English reference':'Supplied English source description')}</summary><p lang="en" dir="ltr">${baEsc(p.referenceExcerpt||p.standardLocation)}</p></details>${adReview(c)}${baRefs(['who','acupuncture',...(practical?[practical.source]:[])])}<p class="ba-fine">${baT('סכמת לימוד והתמצאות; אינה מדריך לביצוע דיקור או טיפול עצמי.','An educational orientation chart; not a guide to needling or self-treatment.')}</p><button class="btn ${isFav(key)?'':'ghost'}" data-fav="${key}">${isFav(key)?t('inFav'):t('addFav')}</button>`;
 store.set('lastItem',key);openSheet();$('#sheet').scrollTop=0;
};
meridianDetail=function(ab){
 adOldMeridian(ab);const step=BA.meridians[ab].steps[baStep],codes=D.points.filter(p=>p.m===ab&&+p.c.split(' ')[1]>=step[0]&&+p.c.split(' ')[1]<=step[1]).map(p=>p.c),views=[...new Set(codes.map(c=>AD.points[c].view))];
 if(!views.includes(adChannelView))adChannelView=views[0];const local=codes.filter(c=>AD.points[c].view===adChannelView);
 const card=$('.ba-route-card');if(!card)return;
 card.innerHTML=`<div class="ba-route-title">${baT('המקטע שנבחר','Selected segment')} · <b dir="ltr">${ab} ${step[0]}–${step[1]}</b></div><div class="ad-tools">${views.map(v=>`<button class="chip ${v===adChannelView?'active':''}" data-ad-channel-view="${v}" aria-pressed="${v===adChannelView}">${adViewTitle(v)}</button>`).join('')}</div>${adDiagram(adChannelView,{codes:local,arrows:true})}<p class="ba-fine">${baT('החצים מחברים נקודות עוקבות במבט הזה לפי סדר המספור. הם אינם מתארים עומק, כלי דם או הסתעפויות פנימיות.','Arrows connect consecutive points in this view by numbering order. They do not depict depth, blood vessels or internal branches.')}</p><details class="ba-refs"><summary>${baT('סקירת המסלול המלא','Whole-channel overview')}</summary>${baMeridianDiagram(ab)}</details>`;
};
function adCompareStart(c){adCompareA=c;adCompareB=adNeighbors(c).find(x=>x!==c)||'PC 6';baLearnTab='compare';closeSheet();route('learn');}
function adCompare(){
 if(adCompareA===adCompareB)adCompareB=adNeighbors(adCompareA).find(c=>c!==adCompareA)||'PC 6';
 const a=adPoint(adCompareA),b=adPoint(adCompareB),da=AD.points[a.c],db=AD.points[b.c],shared=da.landmarks.filter(l=>db.landmarks.some(m=>m.en.toLowerCase()===l.en.toLowerCase()));
 const options=c=>D.points.map(p=>`<option value="${p.c}" ${p.c===c?'selected':''}>${p.c} · ${baEsc(baName(p))}</option>`).join('');
 $('#learnBody').innerHTML=`<div class="ad-compare-controls"><label>${baT('נקודה ראשונה','First point')}<select id="ad-compare-a">${options(a.c)}</select></label><label>${baT('נקודה שנייה','Second point')}<select id="ad-compare-b">${options(b.c)}</select></label></div><div class="ad-tools">${adNeighbors(a.c).filter(c=>c!==a.c).map(c=>`<button class="chip" data-ad-compare-b="${c}" dir="ltr">${c}</button>`).join('')}<button class="chip" data-ad-pair="SI 2|SI 3">SI 2 ↔ SI 3</button><button class="chip" data-ad-pair="PC 6|PC 7">PC 6 ↔ PC 7</button><button class="chip" data-ad-pair="KI 3|KI 6">KI 3 ↔ KI 6</button></div><div class="ad-comparison">${[a,b].map(p=>`<article class="card ad-compare-card"><span class="ba-code" dir="ltr">${p.c}</span><h2>${baEsc(baName(p))}</h2>${adDiagram(AD.points[p.c].view,{codes:da.view===db.view?[a.c,b.c]:[p.c],selected:p.c,focus:true})}<h3>${baT('המיקום','Location')}</h3><p>${baEsc(baT(p.heL,p.referenceExcerpt||p.standardLocation))}</p>${adLandmarks(p.c)}<p class="ba-fine">WHO 2008 · ${baT('הפניית המקור לעמ׳ ','source page ')}${AD.points[p.c].page}</p><button class="chip" data-open="point:${p.c}">${baT('לכרטיס המלא','Full card')}</button></article>`).join('')}</div><div class="card ba-pad"><h3>${baT('מה משותף ומה מבחין?','What is shared and what differs?')}</h3><p>${shared.length?baT('ציוני דרך משותפים: ','Shared landmarks: ')+shared.map(l=>baEsc(baT(l.he,l.en))).join(' · '):baT('ברשומות האלו לא מופיעים ציוני דרך משותפים. התחילו בהשוואת אזור הגוף והמבט.','These records have no shared landmark labels. Begin by comparing region and view.')}</p><p>${baT('קראו בכל תיאור את הצד, היחס למפרק או לגיד והמרחק היחסי. ההדגשה בתרשים מסייעת לזכור את ההבדל; מיקום על המסך אינו מדידה על הגוף.','Read the side, relation to the joint or tendon, and relative distance in each description. The highlight helps recall the difference; screen position is not a body measurement.')}</p>${[a.c,b.c].includes('SI 2')&&[a.c,b.c].includes('SI 3')?`<p><b>${baT('SI 2 נמצאת דיסטלית למפרק החמישי; SI 3 נמצאת פרוקסימלית לו. זה ההבדל המרכזי בין שתי הרשומות המתוקנות.','SI 2 is distal to the fifth metacarpophalangeal joint; SI 3 is proximal to it. This is the key distinction in the corrected records.')}</b></p>`:''}</div>`;
 $('#ad-compare-a').onchange=e=>{adCompareA=e.target.value;adCompare();};$('#ad-compare-b').onchange=e=>{adCompareB=e.target.value;adCompare();};
}
function adQuizBuild(){
 const candidates=baShuffle(D.points.filter(p=>!['perineum','mouth','scalp'].includes(AD.points[p.c].view)).map(p=>p.c));const questions=[];
 for(const c of candidates){const pos=adXY(c),view=AD.points[c].view,pool=baShuffle(D.points.filter(p=>p.c!==c&&AD.points[p.c].view===view).map(p=>p.c)),choices=[c];
  for(const other of pool){const xy=adXY(other);if(choices.every(k=>{const q=adXY(k);return Math.hypot(xy.x-q.x,xy.y-q.y)>=90;}))choices.push(other);if(choices.length===4)break;}
  if(choices.length===4)questions.push({code:c,view,choices:baShuffle(choices),answer:null});if(questions.length===8)break;
 }
 return {questions,index:0,score:0,saved:false};
}
function adQuizRender(){
 const el=$('#learnBody');if(!adQuiz)adQuiz=adQuizBuild();const q=adQuiz.questions[adQuiz.index];
 if(!q){if(!adQuiz.saved){store.set('lastVisualQuiz',{score:adQuiz.score,total:8,date:new Date().toISOString()});adQuiz.saved=true;}el.innerHTML=`<div class="ba-flash card"><span class="eyebrow">${baT('סיכום זיהוי חזותי','Visual identification results')}</span><h2>${adQuiz.score} / 8</h2><p>${baT('התרגול בודק זיכרון של סכמות הלימוד, ואינו הסמכה לאיתור קליני.','This checks recall of the teaching schematics, not clinical locating competence.')}</p>${adQuiz.questions.map(x=>`<details class="ba-refs"><summary>${x.choices[x.answer]===x.code?'✓':'↻'} <b dir="ltr">${x.code}</b></summary><p>${baEsc(baT(adPoint(x.code).heL,adPoint(x.code).standardLocation))}</p><button class="chip" data-open="point:${x.code}">${baT('לכרטיס הנקודה','Point card')}</button></details>`).join('')}<button class="btn" data-ad-quiz-restart>${baT('סבב חדש','New round')}</button></div>`;return;}
 const answered=q.answer!==null,correct=q.choices[q.answer]===q.code,p=adPoint(q.code),last=store.get('lastVisualQuiz',null);
 el.innerHTML=`<div class="ad-quiz"><div class="ad-quiz-top"><span class="ba-tag">${baT('זיהוי חזותי','Visual identification')} · <b dir="ltr">${adQuiz.index+1} / 8</b></span><span>${adQuiz.score} ${baT('נכונות','correct')}</span></div><h2>${baT('איזה סימון מתאים ל־','Which marker is ')}<b dir="ltr">${q.code}</b>?</h2><p>${baEsc(adViewTitle(q.view))} · ${baT('בחרו אות על המפה או בכפתורים שמתחתיה.','Select a letter on the chart or below it.')}</p>${adDiagram(q.view,{codes:q.choices,answers:answered?null:['A','B','C','D'],selected:answered?q.code:'',labels:answered,interactive:!answered})}<div class="ad-answers">${q.choices.map((c,i)=>`<button class="btn ghost ${answered&&c===q.code?'ad-correct':''} ${answered&&q.answer===i&&c!==q.code?'ad-incorrect':''}" data-ad-answer="${i}" ${answered?'disabled':''}>${String.fromCharCode(65+i)}${answered?' · '+c:''}</button>`).join('')}</div><div id="ad-feedback" role="status" aria-live="polite">${answered?`<h3>${correct?baT('נכון','Correct'):baT('נחזור על המיקום','Review the location')}</h3><p>${baEsc(baT(p.heL,p.referenceExcerpt||p.standardLocation))}</p>${adLandmarks(q.code)}<button class="btn" data-ad-quiz-next>${baT(adQuiz.index===7?'לתוצאות':'לשאלה הבאה',adQuiz.index===7?'Results':'Next question')}</button>`:''}</div>${!answered?`<details class="ba-refs"><summary>${baT('רמז: תיאור המיקום','Hint: location description')}</summary><p>${baEsc(baT(p.heL,p.referenceExcerpt||p.standardLocation))}</p></details>`:''}${last?`<p class="ba-fine">${baT('בסבב הקודם','Previous round')}: ${last.score} / 8</p>`:''}</div>`;
}
function adQuizAnswer(index){const q=adQuiz?.questions[adQuiz.index];if(!q||q.answer!==null||!Number.isInteger(index)||index<0||index>3)return;q.answer=index;if(q.choices[index]===q.code)adQuiz.score++;adQuizRender();$('#ad-feedback').scrollIntoView({block:'nearest',behavior:'smooth'});$('[data-ad-quiz-next]')?.focus({preventScroll:true});}
learnScreen=function(){adOldLearn();const tabs=$('.ba-learning-tabs');tabs.insertAdjacentHTML('beforeend',[['visual','זיהוי על המפה','Visual identification'],['compare','השוואת נקודות','Compare points']].map(([k,h,e])=>`<button class="chip ${baLearnTab===k?'active':''}" data-ba-tab="${k}" aria-pressed="${baLearnTab===k}">${baT(h,e)}</button>`).join(''));if(baLearnTab==='visual')adQuizRender();if(baLearnTab==='compare')adCompare();};
flashcard=function(){adOldFlash();const figure=$('#learnBody .ba-plate');if(figure&&flashCard)figure.outerHTML=adDiagram(AD.points[flashCard.c].view,{codes:[flashCard.c],selected:flashCard.c,labels:flashFlipped,focus:true,interactive:false});};
aboutScreen=function(){adOldAbout();$('#view .screen').insertAdjacentHTML('beforeend',`<section class="card ba-pad"><h2>${baT('מהדורה 3.3 · לימוד חזותי','Version 3.3 · visual learning')}</h2><p>${baT('361 סימוני נקודות ב־22 סכמות אזוריות, השוואת נקודות, תרגילי זיהוי וציוני דרך בשתי שפות.','361 point markers in 22 regional schematics, point comparisons, identification exercises and bilingual landmarks.')}</p><a href="point-atlas.html" target="_blank" rel="noopener">${baT('גלריית הסכמות','Schematic gallery')} ↗</a> · <a href="review-register.html" target="_blank" rel="noopener">${baT('יומן בדיקת המקורות','Source review register')} ↗</a><p>${baT('בוצעה בדיקת שלמות של המאגר ובדיקות חיצוניות ממוקדות בשדות של 12 רשומות. טרם בוצעה סקירה של כל מיקום בידי איש מקצוע מוסמך.','The dataset was checked for completeness, with focused external checks of fields in 12 records. A qualified professional has not reviewed every location.')}</p></section>`);};
const adBackupValidate=baValidateBackup;
const adLanguage=applyLang;
applyLang=function(){adLanguage();$('footer>span').textContent=baT('גרסה 3.3 · למידה חזותית','Version 3.3 · visual learning');$('#sheet').setAttribute('aria-label',baT('פרטי פריט','Entry details'));};
baValidateBackup=function(d){const safe=adBackupValidate(d),q=d.lastVisualQuiz;safe.lastVisualQuiz=q&&Number.isInteger(q.score)&&q.score>=0&&q.score<=q.total&&Number.isInteger(q.total)&&q.total>=1&&q.total<=8&&typeof q.date==='string'?{score:q.score,total:q.total,date:q.date.slice(0,40)}:null;return safe;};
document.addEventListener('click',e=>{
 const b=e.target.closest('[data-ad-labels],[data-ad-zoom],[data-ad-compare],[data-ad-channel-view],[data-ad-compare-b],[data-ad-pair],[data-ad-answer],[data-ad-quiz-next],[data-ad-quiz-restart]');if(!b)return;
 if(b.hasAttribute('data-ad-labels')){adLabels=!adLabels;$('#ad-point-chart').innerHTML=adPointChart();$('[data-ad-labels]').focus();}
 if(b.hasAttribute('data-ad-zoom')){adFocus=!adFocus;$('#ad-point-chart').innerHTML=adPointChart();$('[data-ad-zoom]').focus();}
 if(b.hasAttribute('data-ad-compare'))adCompareStart(b.dataset.adCompare);
 if(b.hasAttribute('data-ad-channel-view')){adChannelView=b.dataset.adChannelView;meridianDetail(curMer);}
 if(b.hasAttribute('data-ad-compare-b')){adCompareB=b.dataset.adCompareB;adCompare();}
 if(b.hasAttribute('data-ad-pair')){[adCompareA,adCompareB]=b.dataset.adPair.split('|');adCompare();}
 if(b.hasAttribute('data-ad-answer'))adQuizAnswer(+b.dataset.adAnswer);
 if(b.hasAttribute('data-ad-quiz-next')){const q=adQuiz?.questions[adQuiz.index];if(q&&q.answer!==null){adQuiz.index++;adQuizRender();$('#learnBody').scrollIntoView({block:'start'});}}
 if(b.hasAttribute('data-ad-quiz-restart')){adQuiz=adQuizBuild();adQuizRender();}
});
document.addEventListener('keydown',e=>{if(!['Enter',' '].includes(e.key))return;const b=e.target.closest('svg [data-ad-answer]'),p=e.target.closest('.ad-marker[data-open]');if(b){e.preventDefault();adQuizAnswer(+b.dataset.adAnswer);}else if(p){e.preventDefault();openItem(p.dataset.open);}});
