'use strict';
const BA=window.ATLAS_EDITORIAL;
const baT=(he,en)=>LANG==='he'?he:en;
const baEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const baNorm=v=>String(v||'').normalize('NFD').replace(/[\u0591-\u05c7\u0300-\u036f\s-]/g,'').toLowerCase();
const baName=p=>baT(p.heN||p.py,p.py);
const baMerName=m=>baT(m.heN,m.name);
const baRegionName=id=>BA.regions[id]?.[LANG==='he'?0:1]||id;
const BA_SOURCES={
 who:['WHO · Point locations, 2008','https://iris.who.int/handle/10665/353407'],
 nomenclature:['WHO · 361 point names','https://www.who.int/publications/i/item/9290611057'],
 acupuncture:['NCCIH · Acupuncture','https://www.nccih.nih.gov/health/acupuncture-what-you-need-to-know'],
 reflexology:['NCCIH · Reflexology','https://www.nccih.nih.gov/health/reflexology'],
 pc6:['MSK · Acupressure for nausea','https://www.mskcc.org/cancer-care/patient-education/acupressure-nausea-and-vomiting'],
 li4:['MSK · Acupressure for pain and headaches','https://www.mskcc.org/cancer-care/patient-education/acupressure-pain-and-headaches'],
 anatomy:['NCI / SEER · Anatomy and physiology','https://training.seer.cancer.gov/anatomy/'],
 brain:['NCI / SEER · Central nervous system','https://training.seer.cancer.gov/anatomy/nervous/organization/cns.html'],
 endocrine:['NCI / SEER · Endocrine glands','https://training.seer.cancer.gov/anatomy/endocrine/glands/'],
 respiratory:['NCI / SEER · Respiratory system','https://training.seer.cancer.gov/anatomy/respiratory/'],
 digestive:['NCI / SEER · Digestive system','https://training.seer.cancer.gov/anatomy/digestive/'],
 urinary:['NCI / SEER · Urinary system','https://training.seer.cancer.gov/anatomy/urinary/components/'],
 heart:['NCI / SEER · Heart','https://training.seer.cancer.gov/anatomy/cardiovascular/heart/'],
 joints:['NCI / SEER · Articulations','https://training.seer.cancer.gov/anatomy/skeletal/articulations.html'],
 lymph:['NCI / SEER · Lymphatic system','https://training.seer.cancer.gov/anatomy/lymphatic/components/'],
 pelvis:['NCI / SEER · Reproductive system','https://training.seer.cancer.gov/anatomy/reproductive/']
};
const BA_ART_NAMES={ 'head-front':['ראש ופנים — מבט קדמי','Head — anterior'], 'head-side':['ראש וצוואר — מבט צדדי','Head — lateral'], 'torso-back':['גב, שכמות ועמוד השדרה','Back and scapulae'], 'arm-palmar':['הגפה העליונה — מבט כפי','Upper limb — palmar view'], 'arm-dorsal':['הגפה העליונה — מבט גבי','Upper limb — dorsal view'], 'leg-front':['הרגל — מבט קדמי','Leg — anterior'], 'leg-medial':['הרגל — מבט פנימי','Leg — medial'], 'leg-lateral':['הרגל — מבט חיצוני','Leg — lateral'], 'leg-back':['הרגל — מבט אחורי','Leg — posterior'], 'feet-soles':['סוליות כפות הרגליים','Plantar surfaces'], 'foot-dorsal':['גב כף הרגל','Dorsal foot'], 'foot-medial':['כף הרגל — מבט פנימי','Medial foot'], 'foot-lateral':['כף הרגל — מבט חיצוני','Lateral foot'],brain:['המוח','Brain'],senses:['עין, אוזן וחלל האף','Eye, ear and nasal cavity'],respiratory:['מערכת הנשימה','Respiratory system'],heart:['הלב','Heart'],digestive:['מערכת העיכול','Digestive system'],urinary:['מערכת השתן','Urinary system'],endocrine:['בלוטות ומערכות הורמונליות','Endocrine context'],spine:['עמוד השדרה','Spine'],joints:['מפרקים','Joints'],lymph:['זרימת הלימפה — תרשים מושגי','Lymph flow — conceptual diagram'],pelvis:['אגן ורצפת האגן','Pelvic context']};
let baRegion='',baStep=0,baSurface='soles',baSelectedZone='',baLastFocus=null,baLearnTab='guide',baAnswered=false,baQuizChoices=[];
const baArtTitle=id=>BA_ART_NAMES[id]?.[LANG==='he'?0:1]||id;
const baArtSrc=id=>'assets/plates/'+id+(id==='lymph'?'.svg':'.webp');
function baPlate(id,caption='',small=false){return `<figure class="ba-plate ${small?'small':''}"><button class="ba-image" data-ba-image="${id}" aria-label="${baEsc(baT('הגדלת האיור: ','Enlarge: ')+baArtTitle(id))}"><img src="${baArtSrc(id)}" alt="${baEsc(baArtTitle(id))}" width="1400" height="933" loading="lazy" decoding="async"><span class="ba-enlarge">↗ ${baT('הגדלה','Enlarge')}</span></button><figcaption><b>${baEsc(caption||baArtTitle(id))}</b><span>${baT('המחשה אנטומית כללית · אינה מפת איתור נקודות','General anatomical illustration · not a point-location chart')}</span></figcaption></figure>`;}
function baRefs(keys=['who']){return `<details class="ba-refs"><summary>${baT('מקורות והמשך קריאה','Sources and further reading')}</summary>${[...new Set(keys)].filter(k=>BA_SOURCES[k]).map(k=>`<a href="${BA_SOURCES[k][1]}" target="_blank" rel="noopener noreferrer">${baEsc(BA_SOURCES[k][0])} ↗</a>`).join('')}</details>`;}
function baSection(title,body,tag=''){return body?`<section class="ba-section">${tag?`<span class="ba-tag">${tag}</span>`:''}<h3>${title}</h3><p>${body}</p></section>`:'';}
function baPointMatches(p,q){return !q||[p.c,p.py,p.zh,p.heN,p.heL,p.heI,p.loc,p.ind,MER_HE[p.m],MER[p.m]?.name,baRegionName(p.region)].some(v=>baNorm(v).includes(q));}
function baHeader(eyebrow,title,sub=''){return `<div class="section-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1>${sub?`<p class="ba-sub">${sub}</p>`:''}</div></div>`;}

homeScreen=function(){
 const last=store.get('lastItem',''),lastPoint=last.startsWith('point:')?D.points.find(p=>last==='point:'+p.c):null;
 $('#view').innerHTML=`<div class="screen"><section class="ba-hero"><div class="ba-hero-copy"><div class="eyebrow">BODY ATLAS · 03.3</div><h1>${baT('להכיר את הגוף.<br>להבין את המפה.','Explore the body.<br>Understand the map.')}</h1><p>${baT('אטלס מאויר לנקודות הגוף, למסלולי המרידיאנים ולמפות כף הרגל. לומדים את המיקום, את ההקשר ואת המונחים — צעד אחר צעד.','An illustrated atlas of body points, channel routes and foot maps. Learn locations, context and terminology, one step at a time.')}</p><div class="ba-actions"><button class="btn" data-go="meridians">${baT('לגלות את המסלולים','Explore channels')} ←</button><button class="btn ghost" data-go="learn">${baT('איך מתחילים?','Start learning')}</button></div><div class="ba-stats"><span><b>361</b>${baT('נקודות גוף','Body points')}</span><span><b>14</b>${baT('מרידיאנים','Channels')}</span><span><b>57</b>${baT('אזורי רפלקסולוגיה','Reflexology zones')}</span></div></div><img src="assets/plates/head-side.webp" alt="${baEsc(baArtTitle('head-side'))}" width="1400" height="933"></section>
 ${lastPoint?`<button class="ba-resume card" data-open="${baEsc(last)}"><span>${baT('להמשיך מהמקום האחרון','Continue exploring')}</span><b dir="auto">${lastPoint.c} · ${baEsc(baName(lastPoint))}</b><span>←</span></button>`:''}
 <div class="ba-entry-grid">${[['points','head-front','361',baT('נקודות הגוף','Body points'),baT('מחפשים לפי קוד, שם או אזור','Search by code, name or region')],['meridians','arm-palmar','14',baT('מסלולי המרידיאנים','Channel routes'),baT('מהנקודה הראשונה עד האחרונה','From the first point to the last')],['reflex','feet-soles','57',baT('מפות כף הרגל','Foot maps'),baT('מבט ברור על השיוכים המסורתיים','A clear view of traditional associations')]].map(([go,art,n,title,sub])=>`<button class="ba-entry" data-go="${go}"><img src="assets/plates/${art}.webp" alt="" width="480" height="320"><div><span>${n} · ${baT('פריטי לימוד','entries')}</span><h2>${title}</h2><p>${sub}</p></div></button>`).join('')}</div>
 <div class="ba-info-row"><div><b>${baT('אנטומיה · מסורת · ראיות','Anatomy · tradition · evidence')}</b><p>${baT('שלושה סוגי מידע, מסומנים בנפרד לאורך האטלס.','Three kinds of information, clearly identified throughout the atlas.')}</p></div><button class="chip" data-ba-lesson="models">${baT('איך קוראים את המידע?','How to read the information')}</button></div>
 <div class="card ready-card"><div><b>${baT('הלמידה והמועדפים נשארים אצלכם','Your learning and favorites stay on this device')}</b><p id="ba-offline-status">${baT('טעינה מקומית זמינה; התקנה ושמירה ללא חיבור דורשות טעינה דרך שרת.','Local viewing is available; installation and offline caching require a server.')}</p></div><button class="btn ghost" data-install>${baT('התקנה במכשיר','Install app')}</button></div><p class="ba-fine">${baT('האטלס מיועד ללימוד ולהתמצאות. תסמינים חדשים או מתמשכים מצריכים בירור רפואי.','An educational reference. New or persistent symptoms need medical assessment.')}</p></div>`;
 baOfflineStatus();
};
async function baOfflineStatus(){const el=$('#ba-offline-status');if(!el)return;if(location.protocol==='file:')return;try{const keys=(await caches.keys()).filter(x=>x.startsWith('body-atlas-v3-'));let ready=false;for(const k of keys){const cache=await caches.open(k);if(await cache.match(new URL('offline-ready',location.href).href)){ready=true;break;}}if(el.isConnected)el.textContent=ready?baT('הגרסה נשמרה במכשיר וזמינה ללא חיבור.','This version is saved and available offline.'):baT('הכנת הגרסה לשימוש ללא חיבור מתבצעת בטעינה הראשונה.','The first load prepares this version for offline use.');}catch{}}

pointsScreen=function(){
 const q=baNorm(query),pts=D.points.filter(p=>(!merFilter||p.m===merFilter)&&(!baRegion||p.region===baRegion)&&baPointMatches(p,q));
 const sameRegion=pts.length>0&&pts.every(p=>p.region===pts[0].region)?pts[0].region:'';const art=baRegion?BA.regions[baRegion][2]:(sameRegion?BA.regions[sameRegion][2]:(merFilter?BA.meridians[merFilter].art:'head-front'));
 $('#view').innerHTML=`<div class="screen">${baHeader('POINT INDEX',baT('ספריית נקודות הגוף','Body point library'),baT('בחרו אזור, סננו לפי מרידיאן או חפשו קוד כגון PC 6.','Choose a region, filter by channel or search a code such as PC 6.'))}<div class="ba-filters"><label>${baT('אזור בגוף','Body region')}<select id="ba-region"><option value="">${baT('כל האזורים','All regions')}</option>${Object.keys(BA.regions).map(k=>`<option value="${k}" ${baRegion===k?'selected':''}>${baRegionName(k)}</option>`).join('')}</select></label><label>${baT('מרידיאן','Channel')}<select id="merfilter"><option value="">${t('allMer')}</option>${D.meridians.map(m=>`<option value="${m.ab}" ${merFilter===m.ab?'selected':''}>${m.ab} · ${baMerName(m)}</option>`).join('')}</select></label><button class="chip" data-ba-reset>${baT('איפוס סינון','Reset filters')}</button></div>
 <div class="ba-workspace ba-points-workspace"><div class="ba-sticky">${baPlate(art)}<div class="card ba-pad"><h3>${baRegion?baRegionName(baRegion):baT('קוראים את המיקום','Reading a location')}</h3><p>${baRegion?BA.regions[baRegion][LANG==='he'?3:4]:baT('האיור מציג את ההקשר האנטומי. בכל כרטיס מופיעים תיאור המיקום, המונחים החשובים והשימושים המסורתיים בנפרד.','The illustration shows anatomical context. Each card separates location, terminology and traditional associations.')}</p><button class="chip" data-ba-tab="glossary">${baT('פתיחת מילון המונחים','Open glossary')}</button></div></div>${listPanel(baT('תוצאות','Results'),pts.map(p=>rowHtml(p.c,baName(p),p.py+' · '+baRegionName(p.region),baMerName(MER[p.m]),'point:'+p.c)),pts.length)}</div></div>`;
 $('#ba-region').onchange=e=>{baRegion=e.target.value;pointsScreen();};$('#merfilter').onchange=e=>{merFilter=e.target.value;pointsScreen();};
};
meridiansScreen=function(){
 if(curMer)return meridianDetail(curMer);
 $('#view').innerHTML=`<div class="screen">${baHeader('CHANNEL ATLAS',baT('14 מסלולים. תמונה רחבה אחת.','14 channels. A broader view.'),baT('כל מסלול מחולק לאזורי גוף, עם רצף הנקודות והסברים להעמקה.','Explore each route by body region, with point sequences and further reading.'))}<div class="ba-mer-grid">${D.meridians.map(m=>`<button class="ba-mer-card" data-mer="${m.ab}"><img src="assets/plates/${BA.meridians[m.ab].art}.webp" alt="" width="480" height="320"><div><span class="ba-code">${m.ab}</span><h2>${baMerName(m)}</h2><p>${m.n} ${t('pts')} · ${baT(BA.meridians[m.ab].theme,'Open the illustrated route')}</p></div></button>`).join('')}</div><p class="ba-fine">${baT('המסלולים מתארים את המודל המסורתי. הם אינם כלי דם או עצבים.','Channels describe a traditional model, not blood vessels or nerves.')}</p></div>`;
};
meridianDetail=function(ab){
 const m=MER[ab],e=BA.meridians[ab];if(!m)return;const i=Math.max(0,Math.min(baStep,e.steps.length-1));baStep=i;const s=e.steps[i],pts=D.points.filter(p=>p.m===ab),part=pts.filter(p=>+p.c.split(' ')[1]>=s[0]&&+p.c.split(' ')[1]<=s[1]);
 $('#view').innerHTML=`<div class="screen"><button class="chip" data-ba-mer-back>← ${t('meridians')}</button>${baHeader(`${ab} · ${m.n} ${t('pts')}`,baMerName(m),baT(e.theme,'Follow the external route'))}<div class="ba-channel-layout"><div class="ba-route-card"><div class="ba-route-title">${baT('מסלול חיצוני — סכמה כללית','External route — overview')}</div>${baMeridianDiagram(ab)}<button class="chip" data-ba-diagram="mer:${ab}">${baT('הגדלת התרשים','Enlarge diagram')}</button><p class="ba-fine">${baT('הקו מציג כיוון כללי בלבד. מיקומי הנקודות מפורטים בכרטיסים. הסתעפויות פנימיות אינן מוצגות.','The line gives general orientation. Cards provide point descriptions. Internal branches are not shown.')}</p></div><div><div class="ba-step-tabs">${e.steps.map((x,j)=>`<button data-ba-step="${j}" class="${j===i?'active':''}" aria-pressed="${j===i}"><b>${j+1}</b>${baRegionName(x[2])}<small dir="ltr">${ab} ${x[0]}${x[1]!==x[0]?'–'+x[1]:''}</small></button>`).join('')}</div>${baPlate(BA.regions[s[2]][2],baRegionName(s[2]))}<div class="card ba-pad"><span class="ba-tag">${baT('רצף לימודי · בחרו נקודה','Learning sequence · select a point')}</span><div class="ba-point-sequence">${part.map(p=>`<button class="chip" data-open="point:${p.c}" aria-label="${baEsc(p.c+' '+baName(p))}" dir="ltr">${p.c}</button>`).join('')}</div><div class="ba-step-actions"><button class="chip" data-ba-step="${i-1}" ${i===0?'disabled':''}>${baT('הקודם','Previous')}</button><span>${i+1} / ${e.steps.length}</span><button class="chip" data-ba-step="${i+1}" ${i===e.steps.length-1?'disabled':''}>${baT('הבא','Next')}</button></div></div></div></div>
 <div class="ba-prose-grid">${baSection(baT('המסלול והמבנה','Route and organization'),baEsc(baT(e.summary,m.desc)))}${baSection(baT('למה הוא משויך במסורת?','Traditional association'),baEsc(baT(m.heAssoc,'The channel belongs to the traditional Chinese medicine model. Its name is not a diagnosis or a claim that every point treats the named organ.')),baT('מסורת','Tradition'))}${baSection(baT('מבט משווה','Compare and learn'),baEsc(baT(e.compare,'Compare the first and last point, the regions crossed and the anatomical landmarks. Point numbers do not represent equal distances.')))}</div>${baRefs(['who','nomenclature','acupuncture'])}<div class="ba-actions"><button class="btn ghost" data-fav="mer:${ab}">${isFav('mer:'+ab)?t('inFav'):t('addFav')}</button></div>${listPanel(baT('כל נקודות המסלול','All points on this channel'),pts.map(p=>rowHtml(p.c,baName(p),baRegionName(p.region),'','point:'+p.c)),pts.length)}</div>`;
};

reflexScreen=function(){
 const views={soles:['סוליות','Soles','feet-soles'],top:['גב כף הרגל','Dorsum','foot-dorsal'],inner:['צד פנימי','Medial','foot-medial'],outer:['צד חיצוני','Lateral','foot-lateral']};
 const q=baNorm(query),zs=D.zones.filter(z=>!q||[z.c,z.he,z.en,z.anatomyHe].some(v=>baNorm(v).includes(q)));
 $('#view').innerHTML=`<div class="screen">${baHeader('FOOT ATLAS',baT('כף הרגל, מקרוב','The foot, up close'),baT('בחרו מבט ולחצו על מספר במפה, או פתחו אזור מהרשימה.','Choose a view and select a map number, or open an entry from the list.'))}<div class="ba-workspace"><div><div class="ba-step-tabs">${Object.entries(views).map(([k,v])=>`<button data-ba-surface="${k}" class="${baSurface===k?'active':''}" aria-pressed="${baSurface===k}">${v[LANG==='he'?0:1]}</button>`).join('')}</div><div class="ba-map-card"><div class="ba-route-title">${baT('מפת שיוכים מסורתית','Traditional association map')}</div>${baFootDiagram(baSurface,baSelectedZone)}<button class="chip" data-ba-diagram="foot:${baSurface}">${baT('הגדלת המפה','Enlarge map')}</button><p class="ba-fine">${baT('המספור נשמר ממפת המקור. הסימונים מציגים אזורים כלליים; גבולות השיוך משתנים בין אסכולות.','Numbers follow the supplied source map. Markers denote broad regions; boundaries differ between schools.')}</p></div>${baPlate(views[baSurface][2],'',true)}<details class="ba-refs"><summary>${baT('איך מבדילים בין המפה לאנטומיה?','Map versus anatomy')}</summary><p>${baT('המפה מציגה שיוכים ברפלקסולוגיה. האיור מציג מבנים אנטומיים כלליים. אין ראיה שמפה זו מאפשרת לאבחן איברים לפי רגישות בכף הרגל.','The map presents reflexology associations; the illustration shows general anatomy. Foot tenderness cannot diagnose the associated organs.')}</p>${baRefs(['reflexology'])}</details></div>${listPanel(baT('אזורי המפה','Map entries'),zs.map(z=>rowHtml(z.c,baT(z.he,z.en),baT(views[z.surface][0],views[z.surface][1]),'','zone:'+z.c)),zs.length)}</div></div>`;
};

function baPointTerms(p){const text=p.heL||'';const matches=[];if(/צוּן|צון|cun/.test(text+' '+p.loc))matches.push(5);if(/רדיאלי|רדיוס|אולנרי|גומד/.test(text))matches.push(4);if(/מדיאלי|מֶדיאלי|לטרלי|פנימי|חיצוני/.test(text))matches.push(2);if(/פרוקסימ|דיסטל/.test(text))matches.push(3);if(/בין.?צלעי|הצלעות/.test(text))matches.push(6);if(/מסרק|כף.היד הראשונה|metacarpal|metatarsal/i.test(text+' '+p.loc))matches.push(7);if(/פטישון|malleolus/i.test(text+' '+p.loc))matches.push(8);return matches.slice(0,3);}
function baPractical(p){
 if(p.c==='PC 6')return {text:baT('בדף ההדרכה של MSK מוצעת אקופרסורה בנקודה זו להקלה על בחילה. מאתרים את האזור בצד הכפי של האמה, בין שני הגידים, במרחק של כשלוש אצבעות מקפל שורש כף היד לכיוון המרפק. מפעילים לחץ נוח בתנועה מעגלית למשך 2–3 דקות, ללא כאב. אין לבצע על עור פצוע, פריחה או סימני זיהום.','MSK describes P-6 acupressure for nausea. Locate the inner forearm between the tendons, about three finger-widths from the wrist crease toward the elbow. Use comfortable circular pressure for 2–3 minutes without pain. Avoid damaged skin, rash or signs of infection.'),source:'pc6'};
 if(p.c==='LI 4')return {text:baT('MSK מתאר עיסוי של האזור שבין האגודל לאצבע המורה בגב היד להקלה על כאב וכאב ראש. מרפים את היד לאחר האיתור ומשתמשים בלחץ נוח ובתנועה מעגלית למשך 2–3 דקות, ללא כאב. לפי ההנחיה אין לבצע בהריון או על עור פצוע, פריחה או סימני זיהום.','MSK describes LI-4 acupressure on the back of the hand between the thumb and index finger for pain and headache relief. Relax the hand after locating the area and use comfortable circular pressure for 2–3 minutes without pain. Do not use during pregnancy or on damaged skin, rash or signs of infection.'),source:'li4'};
 return null;
}
openItem=function(key){
 const [kind,id]=key.split(':');let title='',sub='',body='',art='',refs=[];
 if(kind==='point'){
 const p=D.points.find(x=>x.c===id);if(!p)return;const m=MER[p.m],reg=BA.regions[p.region],idx=D.points.filter(x=>x.m===p.m).findIndex(x=>x.c===id),group=D.points.filter(x=>x.m===p.m),practical=baPractical(p),terms=baPointTerms(p);
 title=baName(p);sub=[p.py,p.zh,baMerName(m)].filter(Boolean).join(' · ');art=reg[2];refs=['who','acupuncture',...(practical?[practical.source]:[])];
 body=baSection(baT('איפה נמצאת הנקודה?','Where is the point?'),baEsc(baT(p.heL,p.standardLocation||p.loc)),baT('מיקום','Location'))+baSection(baT('להבין את האזור','Understand the region'),baEsc(reg[LANG==='he'?3:4]),baT('אנטומיה','Anatomy'));
 if(terms.length)body+=`<details class="ba-refs"><summary>${baT('מונחים בתיאור המיקום','Terms in the location description')}</summary>${terms.map(i=>`<p><b>${baT(BA.glossary[i][0],BA.glossary[i][1])}</b><br>${baT(BA.glossary[i][2],baGlossaryEnglish[i])}</p>`).join('')}</details>`;
 body+=baSection(baT('שיוכים ושימושים במסורת','Traditional associations'),baEsc(baT(p.heI||p.heA, p.ind?('Traditional source indications: '+p.ind):'Traditional indications are not specified in the supplied record.')),baT('מסורת · לא הבטחת השפעה','Tradition · not an effectiveness claim'));
 body+=practical?baSection(baT('הדרכה ייעודית למגע','Point-specific acupressure guidance'),baEsc(practical.text),baT('מקור למטופלים','Patient education source')):baSection(baT('מה לומדים כאן?','Learning focus'),baT('לימוד השם, המיקום והיחס לציוני הדרך. אין להחיל על נקודה זו זמן או עומק לחיצה שניתנו לנקודה אחרת. הנחיה מעשית נבחרת לפי האזור והמצב האישי.','Learn the name, location and relation to landmarks. Do not transfer pressure duration or depth from a different point; practical use needs region-specific and personal guidance.'));
 if(p.heC)body+=`<div class="ba-caution">${baEsc(baT(p.heC,baCautionEnglish(p)))}</div>`;
 body+=`<div class="ba-neighbors"><b>${baT('המשך באותו מסלול','Continue on this channel')}</b><div>${[group[idx-1],group[idx+1]].filter(Boolean).map(x=>`<button class="chip" data-open="point:${x.c}" dir="ltr">${x.c}</button>`).join('')}<button class="chip" data-ba-channel="${p.m}">${baT('המסלול המלא','Full route')}</button></div></div><details class="ba-refs"><summary>${baT('תיאור המקור והשוואת מונחים','Source description and terminology')}</summary><p lang="en" dir="ltr">${baEsc(p.standardLocation)}</p><p>${baT('הפניה מתוך המאגר המצורף: WHO 2008, עמ׳ ','Reference in supplied dataset: WHO 2008, p. ')}${baEsc(p.referencePage)}</p></details>`;
 }else if(kind==='zone'){
 const z=D.zones.find(x=>x.c===id);if(!z)return;title=baT(z.he,z.en);sub=baT('רפלקסולוגיה · אזור '+id,'Reflexology · '+id);art=z.art;refs=['reflexology',BA_SOURCES[z.art]?z.art:'anatomy'];baSelectedZone=id;
 body=baSection(baT('איפה האזור במפה?','Where is this on the map?'),baEsc(baT(z.locationHe,z.locationEn||'Choose “Show on map” to open the relevant view and highlighted region.')))+`<button class="chip" data-ba-zone-map="${z.c}">${baT('הצגה במפה','Show on map')} ↗</button>`+baSection(baT('האיבר או המערכת בגוף','The body structure or system'),baEsc(baT(z.anatomyHe,z.anatomyEn||z.en)),baT('אנטומיה','Anatomy'))+baSection(baT('מה משמעות השיוך?','What does the association mean?'),baT(`במפת הרפלקסולוגיה המצורפת האזור משויך אל ${baEsc(z.he)}. זהו חלק ממודל מסורתי; אין פירושו שאיבר זה נמצא בכף הרגל או שרגישות באזור מצביעה על מחלה בו.`,`In the supplied reflexology map this region is associated with ${baEsc(z.en)}. This traditional association does not mean the organ is in the foot, or that tenderness identifies disease in it.`),baT('מסורת','Tradition'))+baSection(baT('מה אפשר ללמוד מהמגע?','Interpreting touch'),baT('אפשר להבחין במרקם העור, בעומס מקומי ובתחושה נעימה או לא נעימה. נעליים, עור מעובה, פציעה ומבנים מקומיים משפיעים על הרגישות. אין להפעיל כוח כדי ״לשחרר״ איבר לפי המפה.','Touch can reveal local skin texture and comfort or tenderness. Footwear, thickened skin, injury and local structures affect sensitivity. Do not apply force to “release” a mapped organ.'))+baSection(baT('עיסוי נעים של כף הרגל','Comfortable foot massage'),baT('אם העור שלם והתחושה תקינה, אפשר לבחור מגע קל ונעים בכף הרגל. אין צורך לרדוף אחרי כאב או לעמוד בזמן טיפול קבוע. בפצע, נפיחות חדשה, ירידה בתחושה או בעיית זרימת דם יש לקבל הנחיה מותאמת לפני עיסוי.','If skin and sensation are normal, choose light, comfortable contact. There is no need to seek pain or follow a fixed treatment duration. Wounds, new swelling, reduced sensation or circulation problems require tailored advice before massage.'));
 }else if(kind==='mer'){closeSheet();curMer=id;baStep=0;screen='meridians';renderNav();meridianDetail(id);return;}else return;
 const f=isFav(key);$('#sheet').innerHTML=`<button class="x" data-close aria-label="${baT('סגירה','Close')}">✕</button><div class="ba-sheet-code" dir="ltr">${baEsc(id)}</div><h2>${baEsc(title)}</h2><p class="ba-sub">${baEsc(sub)}</p>${baPlate(art,'',true)}${body}${baRefs(refs)}<p class="ba-fine">${baT('האטלס הוא כלי לימוד. טיפול בתסמין אישי דורש התאמה מקצועית.','This atlas is educational. Personal symptoms require tailored care.')}</p><button class="btn ${f?'':'ghost'}" data-fav="${baEsc(key)}">${f?t('inFav'):t('addFav')}</button>`;store.set('lastItem',key);openSheet();$('#sheet').scrollTop=0;
};
function baCautionEnglish(p){if(['ST 17','CV 1','GV 1'].includes(p.c))return 'Anatomical reference / sensitive site. No self-pressure instructions are provided.';return 'This record concerns a sensitive area or special circumstance. Avoid self-treatment and seek tailored professional guidance.';}
openSheet=function(){const s=$('#sheet');if(!s.classList.contains('open'))baLastFocus=document.activeElement;s.inert=false;s.setAttribute('aria-hidden','false');s.classList.add('open');$('#scrim').classList.add('open');document.body.classList.add('ba-sheet-open');s.querySelector('[data-close]')?.focus();};
closeSheet=function(){const s=$('#sheet');s.classList.remove('open');s.setAttribute('aria-hidden','true');s.inert=true;$('#scrim').classList.remove('open');document.body.classList.remove('ba-sheet-open');if(baLastFocus?.isConnected)baLastFocus.focus();};

const baGlossaryEnglish=['Reference posture: upright, facing forward, palms forward. Right and left always belong to the person described.','Anterior faces the front; posterior faces the back. The hand also uses palmar and dorsal.','Medial is closer to the midline; lateral is farther from it. These terms describe relative positions.','Proximal is nearer the limb origin; distal is farther away. The elbow is proximal to the wrist.','Radial is the radius/thumb side; ulnar is the ulna/little-finger side.','A body-relative measure. B-cun divides distances between landmarks; F-cun uses finger proportions. There is no universal conversion to centimetres.','The space between adjacent ribs, numbered after the rib above it.','Metacarpals lie between wrist and fingers; metatarsals between the tarsus and toes.','An ankle bony prominence: the medial malleolus belongs to the tibia and the lateral to the fibula.','A route in the traditional Chinese medicine model, not an identified blood vessel, nerve or anatomical tube.','Manual pressure on specified areas. Distinguish it from needling and from a blanket instruction for every point.','A touch practice using traditional associations between foot or hand regions and other body areas. The map is not a diagnostic test.'];
function baGuideCards(){return BA.lessons.map((l,i)=>`<article class="ba-lesson card"><img src="assets/plates/${l[2]}.webp" alt="" width="600" height="400"><div><span class="eyebrow">${String(i+1).padStart(2,'0')} · ${baT('יסודות','Foundations')}</span><h2>${baT(l[1],baLessonEnglish[i][0])}</h2><p>${baT(l[3],baLessonEnglish[i][1])}</p><details><summary>${baT('דוגמה ושאלת הבנה','Example and check')}</summary><p>${baT(l[4],baLessonEnglish[i][2])}</p><b>${baT(l[5],baLessonEnglish[i][3])}</b><details><summary>${baT('הצגת הסבר','Show explanation')}</summary><p>${baT(l[6],baLessonEnglish[i][4])}</p></details></details><button class="chip" data-ba-read="${l[0]}" aria-pressed="${store.get('readLessons',[]).includes(l[0])}">${store.get('readLessons',[]).includes(l[0])?'✓ ':''}${baT('קראתי והבנתי','Mark as read')}</button></div></article>`).join('');}
const baLessonEnglish=[['How to read a point card','Start with the code, then read the region, side and anatomical landmark. Only then read traditional associations. This keeps location separate from claimed purpose.','PC identifies the Pericardium channel; 6 identifies the point in its sequence. It is not a depth, dose or distance.','What does a point number mean?','Its identifier within that channel’s sequence.'],['Orientation and sides','Directions belong to the body being described. In a front view, the person’s right is on the viewer’s left. Use the thumb and little finger to orient a rotated limb.','Find the thumb side in the illustration, then compare it with the word radial.','Which side is radial?','The radius and thumb side.'],['Relative measurement','Descriptions combine a region, landmark, direction and relative distance. Cun is not a fixed ruler. B-cun uses proportional body distances and F-cun uses finger proportions.','The elbow and wrist creases define a segment before that segment is divided.','Can every cun be converted to a fixed number of centimetres?','No. It is relative to the body and measurement method.'],['Anatomy, tradition and evidence','Anatomy describes structures. Channel and reflexology maps describe traditional models. A clinical study evaluates a specific intervention, population and outcome.','A kidney explanation and a foot-map kidney association are different kinds of information.','Does an organ label on a foot map prove a direct anatomical connection?','No. It is a traditional association.'],['Comparing routes','Compare origins, endpoints, regions and landmarks. Point numbers are not equally spaced positions.','Compare the thumb endpoint of LU, middle-finger endpoint of PC and little-finger endpoint of HT.','What distinguishes routes in the same limb?','Origins, endpoints and relationships to landmarks.'],['Touch with an appropriate source','Some locations are for study only. Do not transfer general pressure instructions to eyes, throat, vessels, wounds or intimate areas. PC 6 and LI 4 cards link to point-specific patient guidance.','Check intact skin and normal sensation. Stop with sharp pain, numbness or worsening. Seek tailored advice for pregnancy, surgery or relevant medical conditions.','Does pressure duration for one point apply to all 361 points?','No. Point-specific advice is not a universal protocol.']];
learnScreen=function(){
 $('#view').innerHTML=`<div class="screen">${baHeader('LEARNING STUDIO',baT('מבינים, מתרגלים וזוכרים','Understand, practice and remember'))}<div class="ba-learning-tabs">${[['guide','מדריכי יסוד','Foundations'],['glossary','מילון מונחים','Glossary'],['flashcards','כרטיסיות','Flashcards'],['quiz','בדיקת הבנה','Knowledge check']].map(([k,h,e])=>`<button class="chip ${baLearnTab===k?'active':''}" data-ba-tab="${k}" aria-pressed="${baLearnTab===k}">${baT(h,e)}</button>`).join('')}</div><div id="learnBody"></div></div>`;
 if(baLearnTab==='guide')$('#learnBody').innerHTML=`<p class="ba-sub" id="ba-read-count">${store.get('readLessons',[]).length} / 6 ${baT('מדריכים שסומנו כנקראו','guides marked as read')}</p><div class="ba-lessons">${baGuideCards()}</div>`;
 if(baLearnTab==='glossary')$('#learnBody').innerHTML=`<div class="ba-glossary">${BA.glossary.map((g,i)=>`<article class="card ba-pad"><span class="ba-tag" dir="ltr">${g[1]}</span><h2>${baT(g[0],g[1])}</h2><p>${baT(g[2],baGlossaryEnglish[i])}</p></article>`).join('')}</div>${baRefs(['who','anatomy','reflexology'])}`;
 if(baLearnTab==='flashcards')flashcard();if(baLearnTab==='quiz'){buildQuiz();quizStep();}
};
flashcard=function(){if(!flashCard)flashCard=D.points[Math.floor(Math.random()*D.points.length)];const p=flashCard;$('#learnBody').innerHTML=`<div class="ba-flash card"><span class="ba-code" dir="ltr">${p.c}</span>${baPlate(BA.regions[p.region][2],'',true)}<h2>${flashFlipped?baEsc(baName(p)):baT('מה שם הנקודה ובאיזה אזור היא נמצאת?','What is the point and its region?')}</h2>${flashFlipped?`<p>${baEsc(baT(p.heL,p.loc))}</p><button class="chip" data-open="point:${p.c}">${baT('לכרטיס המלא','Full card')}</button>`:`<p>${baT('נסו להיזכר לפני הפיכת הכרטיס.','Try to recall before revealing the answer.')}</p>`}<div class="ba-actions"><button class="btn" data-flip>${t('flip')}</button><button class="btn ghost" data-fnext>${t('next')}</button></div></div>`;};
function baShuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
buildQuiz=function(){
 const questions=BA.glossary.map((g,i)=>({q:baT('איזה הסבר מתאים למונח ״'+g[0]+'״?','Which definition matches “'+g[1]+'”?'),answer:baT(g[2],baGlossaryEnglish[i]),wrong:baShuffle(BA.glossary.map((x,j)=>j===i?null:baT(x[2],baGlossaryEnglish[j])).filter(Boolean)).slice(0,3),why:baT(g[2],baGlossaryEnglish[i])}));
 for(const m of D.meridians){const first=D.points.find(p=>p.m===m.ab),last=D.points.filter(p=>p.m===m.ab).at(-1);questions.push({q:baT('באיזה אזור נמצא סיום המספור של '+m.heN+'?','Where is the final numbered point of the '+m.name+'?'),answer:baRegionName(last.region),wrong:baShuffle(Object.keys(BA.regions).filter(k=>k!==last.region).map(baRegionName)).slice(0,3),why:baT('הנקודה האחרונה היא '+last.c+'. '+last.heL,'The final point is '+last.c+'. '+last.loc)});}
 quizSet=baShuffle(questions).slice(0,8).map(q=>({...q,opts:baShuffle([{txt:q.answer,ok:true},...q.wrong.map(txt=>({txt,ok:false}))])}));quizIdx=0;quizScore=0;baAnswered=false;baQuizChoices=[];
};
quizStep=function(){
 if(quizIdx>=quizSet.length){store.set('lastQuiz',{score:quizScore,total:quizSet.length,date:new Date().toISOString()});$('#learnBody').innerHTML=`<div class="ba-flash card"><span class="eyebrow">${baT('סיכום תרגול','Practice summary')}</span><h2>${quizScore} / ${quizSet.length}</h2><p>${baT('חזרו להסברים של השאלות שבהן טעיתם.','Review the explanations for missed questions.')}</p>${quizSet.map((q,i)=>`<details class="ba-refs"><summary>${baQuizChoices[i]===q.opts.findIndex(o=>o.ok)?'✓':'↻'} ${baEsc(q.q)}</summary><p>${baEsc(q.why)}</p></details>`).join('')}<button class="btn" data-ba-quiz-again>${t('again')}</button></div>`;return;}
 const q=quizSet[quizIdx];$('#learnBody').innerHTML=`<div class="ba-flash card"><div class="eyebrow">${quizIdx+1} / ${quizSet.length}</div><div class="progress"><i style="width:${quizIdx/quizSet.length*100}%"></i></div><h2>${baEsc(q.q)}</h2><div class="ba-quiz-opts">${q.opts.map((o,i)=>`<button class="opt ${baAnswered?(o.ok?'correct':(baQuizChoices[quizIdx]===i?'wrong':'')):''}" data-ba-answer="${i}" ${baAnswered?'disabled':''}>${baEsc(o.txt)}</button>`).join('')}</div>${baAnswered?`<div class="ba-answer" role="status"><b>${baT('הסבר','Explanation')}</b><p>${baEsc(q.why)}</p></div><button class="btn" data-ba-quiz-next>${t('next')}</button>`:''}</div>`;
};

function baOpenLightbox(kind){const dialog=document.createElement('dialog');dialog.className='ba-lightbox';let content,title;if(kind.startsWith('mer:')){title=baMerName(MER[kind.split(':')[1]]);content=baMeridianDiagram(kind.split(':')[1]);}else if(kind.startsWith('foot:')){title=baT('מפת כף הרגל','Foot map');content=baFootDiagram(kind.split(':')[1],baSelectedZone);}else{title=baArtTitle(kind);content=`<img src="${baArtSrc(kind)}" alt="${baEsc(title)}">`;}
 dialog.setAttribute('aria-label',title);dialog.innerHTML=`<div class="ba-lightbox-bar"><b>${baEsc(title)}</b><label>${baT('הגדלה','Zoom')} <input type="range" min="100" max="250" step="25" value="100" aria-label="${baT('הגדלה','Zoom')}"></label><button class="chip" data-ba-light-close>${baT('סגירה','Close')} ✕</button></div><div class="ba-lightbox-scroll"><div class="ba-lightbox-media">${content}</div></div>`;document.body.append(dialog);dialog.showModal();dialog.querySelector('[data-ba-light-close]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());dialog.querySelector('input').oninput=e=>dialog.querySelector('.ba-lightbox-media').style.width=e.target.value+'%';dialog.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.ba-map-node')){e.preventDefault();const key=e.target.dataset.open;dialog.close();openItem(key);}});dialog.addEventListener('click',e=>{const node=e.target.closest('[data-open]');if(node){e.stopPropagation();const key=node.dataset.open;dialog.close();openItem(key);}});}
const baOriginalSettings=settingsScreen;
settingsScreen=function(){baOriginalSettings();const input=$('#uname');if(input)input.value=store.get('settings',{}).name||'';};
// The settings renderer escapes the name before inserting it into an HTML attribute.
const baOriginalRoute=route;
route=function(s){closeSheet();baOriginalRoute(s);};
aboutScreen=function(){$('#view').innerHTML=`<div class="screen learn-wrap">${baHeader('BODY ATLAS · 3.3',baT('מקורות, עריכה ואיורים','Sources, editorial work and illustrations'))}<div class="card ba-pad"><h2>${baT('מה כולל האטלס?','What is included?')}</h2><p>${baT('361 נקודות, 14 מסלולים, 57 אזורי רפלקסולוגיה, שישה מדריכי יסוד ומילון מונחים. תיאורי המיקום והשיוכים נבנו על המאגר שסופק לפרויקט; נוספו עריכה, הקשר אנטומי וכלי לימוד.','361 points, 14 channels, 57 reflexology entries, six foundation guides and a glossary. Location and traditional-association records build on the supplied dataset, with new editorial context and learning tools.')}</p><h3>${baT('איך משתמשים באיורים?','Using the illustrations')}</h3><p>${baT('איורי ImageGen מציגים מבנים באופן כללי ועשויים לכלול פישוטים. מפות המסלולים הן סכמות התמצאות; הן אינן תחליף לאיתור אנטומי על אדם. המספור במפות כף הרגל נשמר מהמפה שסופקה.','ImageGen illustrations present general structures and may simplify anatomy. Channel diagrams are orientation schematics, not a substitute for anatomical location on a person. Foot-map numbering follows the supplied map.')}</p><h3>${baT('מסורת וראיות','Tradition and evidence')}</h3><p>${baT('שיוכים מסורתיים מופיעים ככאלה. תקנון שמות ומיקומים אינו הוכחת יעילות רפואית. המידע אינו אבחון אישי או הכשרה לביצוע דיקור. לפני שימוש בהוראה מקצועית יש להשלים סקירה קלינית של התוכן והאיורים.','Traditional associations are labelled. Standardized names and locations do not establish medical efficacy. This is not a diagnosis tool or a qualification to perform needling. Clinical review is needed before professional training use.')}</p><p>${baT('נבדקו מקורות בתאריך 21.09.2026. הפניות WHO בכרטיסים מגיעות מהמאגר שסופק; הן אינן מציינות אימות עצמאי של כל נקודה.','Sources accessed 21 September 2026. WHO page references come from the supplied dataset and do not imply independent validation of every point.')}</p></div>${baRefs(Object.keys(BA_SOURCES))}<div class="card ba-pad"><h3>${baT('ייחוס ושימוש בנתונים','Data provenance')}</h3><p>AppNest / Barak Aflalo · TARA Acupoints Ontology · WHO 2008 · supplied Reflexology-Map chart.</p><p>${baT('דוח הייבוא המקורי מציין שלא נמצא רישיון להפצה מחדש של מאגר TARA. הקבצים מיועדים כאן להמשך העבודה האישית; לפני הפצה ציבורית יש לברר את תנאי המאגר ומפת המקור.','The original import report did not establish redistribution terms for TARA. This package continues the supplied personal project; verify dataset and source-map terms before public redistribution.')}</p><a href="illustration-atlas.html">${baT('גלריית כל האיורים','Illustration gallery')} ↗</a> · <a href="privacy_policy.html">${baT('פרטיות','Privacy')}</a></div></div>`;};

document.addEventListener('click',e=>{
 const b=e.target.closest('[data-ba-image],[data-ba-diagram],[data-ba-surface],[data-ba-step],[data-ba-mer-back],[data-ba-channel],[data-ba-zone-map],[data-ba-tab],[data-ba-lesson],[data-ba-read],[data-ba-answer],[data-ba-quiz-next],[data-ba-quiz-again],[data-ba-reset]');if(!b)return;
 e.preventDefault();e.stopImmediatePropagation();if(b.disabled)return;
 if(b.hasAttribute('data-ba-image'))return baOpenLightbox(b.dataset.baImage);
 if(b.hasAttribute('data-ba-diagram'))return baOpenLightbox(b.dataset.baDiagram);
 if(b.hasAttribute('data-ba-surface')){baSurface=b.dataset.baSurface;return reflexScreen();}
 if(b.hasAttribute('data-ba-step')){baStep=+b.dataset.baStep;return meridianDetail(curMer);}
 if(b.hasAttribute('data-ba-mer-back')){curMer=null;baStep=0;return meridiansScreen();}
 if(b.hasAttribute('data-ba-channel')){const id=b.dataset.baChannel;closeSheet();screen='meridians';curMer=id;baStep=0;renderNav();meridianDetail(id);window.scrollTo(0,0);return;}
 if(b.hasAttribute('data-ba-zone-map')){const z=D.zones.find(x=>x.c===b.dataset.baZoneMap);closeSheet();baSurface=z.surface;baSelectedZone=z.c;screen='reflex';query=$('#q').value='';renderNav();reflexScreen();window.scrollTo(0,0);return;}
 if(b.hasAttribute('data-ba-tab')){baLearnTab=b.dataset.baTab;screen='learn';closeSheet();renderNav();learnScreen();return;}
 if(b.hasAttribute('data-ba-lesson')){baLearnTab='guide';route('learn');const idx=BA.lessons.findIndex(l=>l[0]===b.dataset.baLesson);$$('.ba-lesson')[idx]?.scrollIntoView({block:'start'});return;}
 if(b.hasAttribute('data-ba-read')){const id=b.dataset.baRead;const read=store.get('readLessons',[]);store.set('readLessons',read.includes(id)?read.filter(x=>x!==id):[...read,id]);const on=!read.includes(id);const count=$('#ba-read-count');if(count)count.textContent=store.get('readLessons',[]).length+' / 6 '+baT('מדריכים שסומנו כנקראו','guides marked as read');b.setAttribute('aria-pressed',on);b.textContent=(on?'✓ ':'')+baT('קראתי והבנתי','Mark as read');return;}
 if(b.hasAttribute('data-ba-answer')){if(baAnswered)return;const i=+b.dataset.baAnswer;baQuizChoices[quizIdx]=i;if(quizSet[quizIdx].opts[i].ok)quizScore++;baAnswered=true;quizStep();return;}
 if(b.hasAttribute('data-ba-quiz-next')){quizIdx++;baAnswered=false;quizStep();return;}
 if(b.hasAttribute('data-ba-quiz-again')){buildQuiz();quizStep();return;}
 if(b.hasAttribute('data-ba-reset')){baRegion=merFilter=query='';$('#q').value='';pointsScreen();return;}
},true);
document.addEventListener('click',e=>{if(e.target.closest('[data-mer]'))baStep=0;},true);
document.addEventListener('keydown',e=>{
 if(document.querySelector('dialog[open]'))return;
 if((e.key==='Enter'||e.key===' ')&&e.target.matches('.ba-map-node')){e.preventDefault();openItem(e.target.dataset.open);}
 const s=$('#sheet');if(!s.classList.contains('open'))return;
 if(e.key==='Escape'){e.preventDefault();closeSheet();return;}
 if(e.key==='Tab'){const focus=[...s.querySelectorAll('button:not([disabled]),a[href],summary,input,select,[tabindex="0"]')].filter(x=>x.getClientRects().length);const first=focus[0],last=focus.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
});
$('#q').addEventListener('input',()=>{baRegion='';},true);
const baOldApplyLang=applyLang;
applyLang=function(){baOldApplyLang();$('#q').placeholder=baT('חיפוש קוד, נקודה, מרידיאן או אזור…','Search code, point, channel or region…');$('#q').setAttribute('aria-label',baT('חיפוש באטלס','Search atlas'));};

I18N.he.onbo='בחרו מסלול, נקודה או מפת כף רגל. בכל כרטיס תמצאו מיקום, הקשר אנטומי והסבר לשיוך המסורתי. בהפעלה דרך שרת, הגרסה נשמרת לשימוש ללא חיבור לאחר השלמת הטעינה הראשונה.';
I18N.en.onbo='Choose a channel, point or foot map. Each card explains its location, anatomy and traditional association. When served over HTTP(S), the app becomes available offline after the first complete load.';
I18N.en.aiNote='Questions are sent to the selected AI provider. The API key is stored in this browser. Avoid personal medical information and shared devices.';
const baOldToggleFav=toggleFav;
toggleFav=function(key){baOldToggleFav(key);$$('[data-fav]').filter(b=>b.dataset.fav===key).forEach(b=>{b.textContent=isFav(key)?t('inFav'):t('addFav');b.classList.toggle('ghost',!isFav(key));});};
const baValidKey=k=>typeof k==='string'&&(D.points.some(x=>k==='point:'+x.c)||D.zones.some(x=>k==='zone:'+x.c)||D.meridians.some(x=>k==='mer:'+x.ab));
function baValidateBackup(d){
 if(!d||typeof d!=='object'||Array.isArray(d)||(!Array.isArray(d.favs)&&!d.settings))throw Error('Invalid backup');
 if(d.favs!==undefined&&(!Array.isArray(d.favs)||d.favs.some(k=>!baValidKey(k))))throw Error('Invalid favorites');
 const s=d.settings||{},settings={};if(typeof s!=='object'||Array.isArray(s))throw Error('Invalid settings');
 if(typeof s.name==='string')settings.name=s.name.slice(0,100);
 if(['day','night'].includes(s.theme))settings.theme=s.theme;
 if(PALS.includes(s.pal))settings.pal=s.pal;
 const read=Array.isArray(d.readLessons)?d.readLessons.filter(id=>BA.lessons.some(l=>l[0]===id)):[];
 const q=d.lastQuiz,quiz=q&&Number.isInteger(q.score)&&q.score>=0&&q.score<=8&&q.total===8&&typeof q.date==='string'?{score:q.score,total:8,date:q.date.slice(0,40)}:null;
 return {settings,favs:[...new Set(d.favs||[])],lang:Object.hasOwn(I18N,d.lang)?d.lang:'he',readLessons:[...new Set(read)],lastItem:baValidKey(d.lastItem)?d.lastItem:'',lastQuiz:quiz};
}
doBackup=function(){const d={version:3,settings:store.get('settings',{}),favs,lang:LANG,readLessons:store.get('readLessons',[]),lastItem:store.get('lastItem',''),lastQuiz:store.get('lastQuiz',null),lastVisualQuiz:store.get('lastVisualQuiz',null),learningProgress:store.get('learningProgress',null),visualSession:store.get('visualSession',null),courseProgress:store.get('courseProgress',null),ts:Date.now()};const safe=baValidateBackup(d);const url=URL.createObjectURL(new Blob([JSON.stringify({...safe,version:3,ts:d.ts},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='body-atlas-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
doRestore=function(){const inp=document.createElement('input');inp.type='file';inp.accept='.json,application/json';inp.onchange=async()=>{const f=inp.files?.[0];if(!f)return;try{if(f.size>1000000)throw Error('File too large');const d=baValidateBackup(JSON.parse(await f.text()));for(const [k,v] of Object.entries(d))store.set(k,v);favs=d.favs;LANG=d.lang;if(typeof adQuiz!=='undefined')adQuiz=null;applySettings();applyLang();route('settings');alert(t('restored'));}catch{alert(t('bad'));}};inp.click();};

if('serviceWorker' in navigator)navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.type==='BODY_ATLAS_READY')baOfflineStatus();});
const baLanguageLabels=applyLang;
applyLang=function(){baLanguageLabels();$('#themeBtn').setAttribute('aria-label',baT('מצב תצוגה','Display mode'));$('header [data-go="settings"]').setAttribute('aria-label',t('set'));const footer=$('footer [data-go="about"]');footer.textContent=t('about');for(const el of [footer,$('.brand')]){el.setAttribute('role','button');el.setAttribute('tabindex','0');}};
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[role="button"][data-go]')){e.preventDefault();route(e.target.dataset.go);}});
const baSettingsLabels=settingsScreen;
settingsScreen=function(){baSettingsLabels();$('#lang').setAttribute('aria-label',t('lang'));$$('[data-pal]').forEach(b=>b.setAttribute('aria-label',t('palette')+': '+b.dataset.pal));};
