'use strict';
const AS=window.ATLAS_LEARNING;
let asLandmark=-1,asVariant='primary',asMode='mixed';
const asOldOpen=openItem,asOldStudy=adStudy,asOldReview=adReview,asOldBackup=baValidateBackup;
function asPrimaryText(c){return baT(adPoint(c).heL,AS.points[c].primaryEn);}
function asPointLocation(p){const d=AD.points[p.c],alt=d.alternate;return baSection(baT(asVariant==='alternate'&&alt?'המיקום החלופי המוצג':'המיקום הראשי',asVariant==='alternate'&&alt?'Displayed alternative location':'Primary location'),baEsc(asVariant==='alternate'&&alt?baT(alt.he,alt.en):asPrimaryText(p.c)),baT('תיאור מיקום','Location description'));}
adLandmarks=function(c){return `<div class="ad-landmarks as-landmarks" aria-label="${baT('ציוני דרך להדגשה','Landmarks to highlight')}">${AD.points[c].landmarks.map((l,i)=>`<button type="button" class="chip" data-as-landmark="${c}|${i}" aria-pressed="${adCurrent===c&&asLandmark===i}">${baEsc(baT(l.he,l.en))}<span aria-hidden="true"> ⊙</span></button>`).join('')}</div>`;};
function asAltMark(c){const p=AD.points[c].alternate,x=p.view==='handPalm'?1000-p.x:p.x,side=x>600?-1:1,dy=side<0?-40:52;return `<g class="as-alt-marker" aria-label="${baT('מיקום חלופי','Alternative location')}"><path d="M${x} ${p.y-15}L${x+15} ${p.y}L${x} ${p.y+15}L${x-15} ${p.y}Z"/><path class="as-alt-leader" d="M${x+15*side} ${p.y}L${x+52*side} ${p.y+dy}"/><text text-anchor="${side<0?'end':'start'}" x="${x+56*side}" y="${p.y+dy+7}" class="ad-point-label">${baT('חלופה','ALT')}</text></g>`;}
function asHipLines(c){if(!['GB 29','GB 30'].includes(c))return '';return `<g class="as-reference-lines" aria-hidden="true"><path d="M650 630 L270 520" class="as-primary-line"/><path d="M650 630 L730 260" class="as-alternate-line"/></g>`;}
function asLandmarkCaption(c){if(asLandmark<0)return '';const l=AD.points[c].landmarks[asLandmark],shape=alResolve(c,asLandmark);if(!l||!shape)return '';const projection=shape.kind==='projection'||(AD.points[c].view==='handPalm'&&/nail/i.test(l.en));return `<div class="as-landmark-caption" role="status"><b>${baEsc(baT(l.he,l.en))}</b><p>${baT(projection?'ההדגשה מציגה היטל או גובה ייחוס בסכמה; המבנה עצמו אינו בהכרח נראה מפני השטח במבט הזה.':shape.kind==='region'?'ההדגשה מציגה אזור כללי, ולא את גבולותיו המדויקים על גוף.':shape.kind==='reference'?'זהו קו או גובה ייחוס לקריאת המיקום.':'ההדגשה מציגה את אזור המבנה בסכמת הלימוד; היא אינה מדידה אנטומית.',projection?'This highlights a projected reference or level. The structure may not be visible from this surface.':shape.kind==='region'?'This highlights a broad region, not its precise boundaries on a person.':shape.kind==='reference'?'This is a reference line or level used to read the location.':'This highlights the structure region on the teaching schematic, not an anatomical measurement.')}</p><button class="chip" data-as-clear-landmark>${baT('הסרת הדגשה','Clear highlight')}</button></div>`;}
adPointChart=function(){
 const c=adCurrent,d=AD.points[c];if(!d)return '';const alt=d.alternate,kind=asVariant==='alternate'&&alt?'alternate':'primary';
 const controls=`<div class="ad-tools"><button class="chip" data-ad-labels aria-pressed="${adLabels}">${baT(adLabels?'הסתרת שמות':'הצגת שמות',adLabels?'Hide labels':'Show labels')}</button><button class="chip" data-ad-zoom aria-pressed="${adFocus}">${baT(adFocus?'מבט מלא':'תקריב',adFocus?'Full view':'Close-up')}</button><button class="chip" data-ad-compare="${c}">${baT('השוואת נקודות','Compare points')}</button></div>`;
 const tabs=alt?`<div class="as-variant-tabs" role="group" aria-label="${baT('בחירת מיקום','Location choice')}">${[['primary','ראשי','Primary'],['alternate','חלופי','Alternative'],['both','השוואת החלופות','Compare locations']].map(([key,h,e])=>`<button class="chip" data-as-variant="${key}" aria-pressed="${asVariant===key}">${baT(h,e)}</button>`).join('')}</div>`:'';
 const overlay=(asLandmark>=0?alOverlay(c,asLandmark):'')+asHipLines(c);
 let charts='';
 if(alt&&asVariant==='both'&&(alt.view!==d.view||d.view==='face')){charts=`<div class="as-dual"><div><b>${baT('ראשי','Primary')}</b>${adDiagram(d.view,{codes:[c],selected:c,labels:adLabels,focus:adFocus,frame:d.view==='face'&&adFocus?[325,415,350,350]:null})}</div><div><b>${baT('חלופי','Alternative')}</b>${adDiagram(alt.view,{codes:[c],selected:c,positions:{[c]:alt},labels:adLabels,focus:adFocus,frame:d.view==='face'&&adFocus?[325,415,350,350]:null})}</div></div>`;}
 else charts=adDiagram(kind==='alternate'?alt.view:d.view,{codes:kind==='alternate'?[c]:adNeighbors(c),selected:c,labels:adLabels,focus:adFocus,frame:d.view==='hip'&&asVariant==='both'?[180,180,630,600]:null,positions:kind==='alternate'?{[c]:alt}:{},overlay:kind==='alternate'?asHipLines(c):overlay,afterNodes:alt&&asVariant==='both'?asAltMark(c):''});
 return controls+tabs+charts+asLandmarkCaption(c)+(alt?`<div class="as-variant-note"><b>${baT(asVariant==='primary'?'המיקום הראשי מסומן בטורקיז':asVariant==='alternate'?'המיקום החלופי מוצג כעת':'ראשי וחלופי הם שתי הגדרות מהמקור',asVariant==='primary'?'Primary location shown in turquoise':asVariant==='alternate'?'Alternative location is displayed': 'Primary and alternative are separate source definitions')}</b><p>${baEsc(baT(alt.he,alt.en))}</p>${asVariant==='both'&&alt.view===d.view&&d.view!=='face'?`<p>${baT('הטבעת בטורקיז היא המיקום הראשי; המעוין הענברי הוא החלופה. ההפרדה בסכמה אינה סרגל מדידה.','Turquoise ring: primary. Amber diamond: alternative. Schematic separation is not a measuring scale.')}</p>`:''}</div>`:`<p class="ba-fine">${baT('הטבעת מסמנת את הנקודה. לחצו על ציון דרך ברשימה כדי להדגיש את המבנה שאליו מתייחס התיאור.','The ring marks the point. Select a landmark below to highlight the structure referenced in the description.')}</p>`);
};
adStudy=function(c){const n=AS.points[c],p=adPoint(c),q=adPoint(n.compare);return `<section class="ba-section as-study"><span class="ba-tag">${baT('קריאה ממוקדת · '+c,'Focused reading · '+c)}</span><h3>${baT('מה חשוב להבחין כאן?','What distinguishes this location?')}</h3><p>${baEsc(baT(n.focus.he,n.focus.en))}</p><div class="as-anchor"><span>${baT('ציון דרך להתחיל ממנו','Start with this reference')}</span><button class="chip" data-as-landmark="${c}|${n.anchor}">${baEsc(baT(AD.points[c].landmarks[n.anchor].he,AD.points[c].landmarks[n.anchor].en))} ⊙</button></div><h3>${baT('ציוני הדרך בתיאור','Landmarks in the description')}</h3><p class="ba-fine">${baT('בחרו שם כדי להדגיש אותו בתרשים.','Choose a name to highlight it on the chart.')}</p>${adLandmarks(c)}<details class="ba-refs as-contrast"><summary>${baT('להבחין בין ','Distinguish ')}<b dir="ltr">${c} ↔ ${q.c}</b></summary><div><h4 dir="ltr">${c}</h4><p>${baEsc(asPrimaryText(c))}</p></div><div><h4 dir="ltr">${q.c}</h4><p>${baEsc(asPrimaryText(q.c))}</p></div><button class="chip" data-ad-compare="${c}">${baT('השוואה עם שני תרשימים','Compare both charts')}</button></details></section>`;};
adCompareStart=function(c){adCompareA=c;adCompareB=AS.points[c].compare;baLearnTab='compare';closeSheet();route('learn');};
adReview=function(c){const d=AD.points[c];return asOldReview(c)+((d.check32||d.correction32)?`<details class="ba-refs"><summary>${baT('בדיקה נוספת במהדורה 3.2','Additional version 3.2 check')}</summary><p>${baT(d.correction32?'שם השריר שיובא הוחלף ב״מרווח בין־גרמי״ בהתאם לתיאור המקור ולקטע WHO המאונדקס.':'תיאור חלופת המיקום הושווה לקטע WHO המאונדקס ברשת.',d.correction32?'The imported muscle label was replaced by “interosseous space”, matching the supplied location text and indexed WHO excerpt.':'The alternative-location description was compared with the indexed WHO excerpt.')}</p><p>${baT('זו בדיקת טקסט ממוקדת. היא אינה אישור קליני של הסימון או של האיור.','This is a focused text check, not clinical approval of a marker or illustration.')}</p></details>`:'');};
openItem=function(key){if(key.startsWith('point:')){asLandmark=-1;asVariant='primary';}asOldOpen(key);};
function asRefreshChart(){const el=$('#ad-point-chart');if(!el||!AD.points[adCurrent])return;el.innerHTML=adPointChart();const loc=$('#as-location');if(loc)loc.innerHTML=asPointLocation(adPoint(adCurrent));$$('#sheet [data-as-landmark]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.asLandmark===adCurrent+'|'+asLandmark));}
function asHighlight(c,i){if(!AD.points[c]?.landmarks[i]||!alResolve(c,i))return;if(adCurrent!==c||!$('#sheet').classList.contains('open'))openItem('point:'+c);asLandmark=i;asVariant='primary';adFocus=false;asRefreshChart();$('#ad-point-chart').scrollIntoView({block:'start',behavior:'smooth'});}

// Only aggregate learning records are stored. No medical or treatment records.
function asEmptyProgress(){return {version:1,points:{},rounds:[]};}
function asValidDate(s){return typeof s==='string'&&s.length<=40&&Number.isFinite(Date.parse(s));}
function asValidateProgress(value){if(value==null)return asEmptyProgress();if(typeof value!=='object'||Array.isArray(value)||value.version!==1||!value.points||typeof value.points!=='object'||Array.isArray(value.points)||!Array.isArray(value.rounds)||value.rounds.length>30)throw Error('Invalid learning progress');const clean=asEmptyProgress();
 for(const [c,p]of Object.entries(value.points)){if(!Object.hasOwn(AD.points,c)||!p||typeof p!=='object')throw Error('Invalid progress point');for(const k of ['attempts','correct','wrong','streak','assisted'])if(!Number.isInteger(p[k])||p[k]<0||p[k]>100000)throw Error('Invalid progress counter');if(p.attempts!==p.correct+p.wrong||p.streak>p.correct||p.assisted>p.attempts||!asValidDate(p.lastSeen)||!asValidDate(p.nextDue)||(p.confusedWith!==null&&!Object.hasOwn(AD.points,p.confusedWith)))throw Error('Inconsistent progress');clean.points[c]={attempts:p.attempts,correct:p.correct,wrong:p.wrong,streak:p.streak,assisted:p.assisted,lastSeen:p.lastSeen,nextDue:p.nextDue,confusedWith:p.confusedWith};}
 for(const r of value.rounds){if(!r||typeof r.id!=='string'||r.id.length>80||!Number.isInteger(r.total)||r.total<1||r.total>8||!Number.isInteger(r.score)||r.score<0||r.score>r.total||!asValidDate(r.date)||!['mixed','review'].includes(r.mode))throw Error('Invalid round');if(!clean.rounds.some(x=>x.id===r.id))clean.rounds.push({id:r.id,total:r.total,score:r.score,date:r.date,mode:r.mode});}return clean;
}
function asProgress(){try{return asValidateProgress(store.get('learningProgress',null));}catch{return asEmptyProgress();}}
function asValidateSession(v){if(!v)return null;if(typeof v!=='object'||!['3.2.0','3.3.0'].includes(v.version)||typeof v.id!=='string'||v.id.length>80||!['mixed','review'].includes(v.mode)||!Array.isArray(v.questions)||v.questions.length<1||v.questions.length>8||!Number.isInteger(v.index)||v.index<0||v.index>v.questions.length)return null;
 const questions=[];for(const q of v.questions){if(!q||!Object.hasOwn(AD.points,q.code)||q.view!==AD.points[q.code].view||!Array.isArray(q.choices)||q.choices.length<2||q.choices.length>4||new Set(q.choices).size!==q.choices.length||!q.choices.includes(q.code)||q.choices.some(c=>!Object.hasOwn(AD.points,c)||AD.points[c].view!==q.view)||(q.answer!==null&&(!Number.isInteger(q.answer)||q.answer<0||q.answer>=q.choices.length)))return null;questions.push({code:q.code,view:q.view,choices:[...q.choices],answer:q.answer,hinted:!!q.hinted});}
 if(new Set(questions.map(q=>q.code)).size!==questions.length||questions.some((q,i)=>(i<v.index&&q.answer===null)||(i>v.index&&q.answer!==null)))return null;
 return {version:'3.3.0',id:v.id,mode:v.mode,questions,index:v.index,score:questions.filter(q=>q.answer!==null&&q.choices[q.answer]===q.code).length,saved:false,reviewCount:Number.isInteger(v.reviewCount)&&v.reviewCount>=0&&v.reviewCount<=questions.length?v.reviewCount:0};
}
function asNeedsReview(p,now=Date.now()){return !!p&&((p.wrong>0&&p.streak<2)||Date.parse(p.nextDue)<=now);}
function asRecordAnswer(q){const all=asProgress(),now=new Date(),ok=q.choices[q.answer]===q.code,old=all.points[q.code]||{attempts:0,correct:0,wrong:0,streak:0,assisted:0,confusedWith:null},streak=ok&&!q.hinted?old.streak+1:0;
 const days=ok&&!q.hinted?[1,3,7,14][Math.min(streak-1,3)]:0;all.points[q.code]={attempts:old.attempts+1,correct:old.correct+(ok?1:0),wrong:old.wrong+(ok?0:1),streak,assisted:old.assisted+(q.hinted?1:0),lastSeen:now.toISOString(),nextDue:new Date(+now+days*86400000).toISOString(),confusedWith:ok?old.confusedWith:q.choices[q.answer]};store.set('learningProgress',all);
}
function asCandidates(c){const view=AD.points[c].view,choices=[c],pool=baShuffle(D.points.filter(p=>p.c!==c&&AD.points[p.c].view===view).map(p=>p.c));for(const x of pool){const pos=adXY(x);if(choices.every(k=>{const p=adXY(k);return Math.hypot(p.x-pos.x,p.y-pos.y)>=75;}))choices.push(x);if(choices.length===4)break;}return choices.length>=2?choices:null;}
adQuizBuild=function(){const progress=asProgress(),eligible=baShuffle(D.points.filter(p=>!['perineum','mouth'].includes(AD.points[p.c].view)).map(p=>p.c));const review=eligible.filter(c=>asNeedsReview(progress.points[c])).sort((a,b)=>{const x=progress.points[a],y=progress.points[b];return (y.wrong>0&&y.streak<2?1000:0)-(x.wrong>0&&x.streak<2?1000:0)+(y.wrong-x.wrong);});const fresh=eligible.filter(c=>!progress.points[c]),others=eligible.filter(c=>!review.includes(c)&&!fresh.includes(c));let order=asMode==='review'?[...review,...fresh,...others]:[...review.slice(0,4),...fresh,...review.slice(4),...others];const questions=[];
 for(const c of [...new Set(order)]){const choices=asCandidates(c);if(choices)questions.push({code:c,view:AD.points[c].view,choices:baShuffle(choices),answer:null,hinted:false});if(questions.length===8)break;}
 return {version:'3.3.0',id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10),mode:asMode,questions,index:0,score:0,saved:false,reviewCount:questions.filter(q=>asNeedsReview(progress.points[q.code])).length};
};
function asQuizToolbar(){const p=asProgress(),review=Object.entries(p.points).filter(([,r])=>asNeedsReview(r));return `<section class="as-progress"><div class="as-progress-stats"><span><b>${Object.keys(p.points).length}</b>${baT('נקודות שתורגלו','points practiced')}</span><span><b>${review.length}</b>${baT('נקודות לחזרה','points to review')}</span><span><b>${p.rounds.length}</b>${baT('סבבים שמורים','saved rounds')}</span></div><div class="ad-tools"><button class="chip" data-as-mode="mixed" aria-pressed="${asMode==='mixed'}">${baT('סבב משולב','Mixed round')}</button><button class="chip" data-as-mode="review" aria-pressed="${asMode==='review'}">${baT('חזרה על טעויות','Review mistakes')}</button></div><p class="ba-fine">${baT('טעויות חוזרות מוקדם יותר. הצלחה ללא רמז מרווחת את החזרה ליום, 3, 7 ועד 14 ימים. אלה כללי תרגול, ולא הערכה מקצועית.','Mistakes return sooner. Unaided success spaces review by 1, 3, 7 and up to 14 days. These are practice rules, not professional assessment.')}</p>${review.length?`<details class="ba-refs"><summary>${baT('הנקודות שכדאי לחזור אליהן','Your review list')}</summary><div class="ad-tools">${review.slice(0,20).map(([c,r])=>`<button class="chip" data-open="point:${c}"><b dir="ltr">${c}</b> · ${r.wrong} ${baT('טעויות','misses')}</button>`).join('')}</div></details>`:''}</section>`;}
function asSaveSession(){if(adQuiz&&!adQuiz.saved)store.set('visualSession',adQuiz);}
adQuizRender=function(){if(!adQuiz){adQuiz=asValidateSession(store.get('visualSession',null))||adQuizBuild();asMode=adQuiz.mode;}const el=$('#learnBody'),q=adQuiz.questions[adQuiz.index],total=adQuiz.questions.length;
 if(!q){if(!adQuiz.saved){const p=asProgress(),date=new Date().toISOString();if(!p.rounds.some(r=>r.id===adQuiz.id)){p.rounds.push({id:adQuiz.id,mode:adQuiz.mode,score:adQuiz.score,total,date});p.rounds=p.rounds.slice(-30);store.set('learningProgress',p);}store.set('lastVisualQuiz',{score:adQuiz.score,total,date});adQuiz.saved=true;store.set('visualSession',null);}el.innerHTML=asQuizToolbar()+`<section class="ba-flash card"><span class="eyebrow">${baT('סיכום סבב','Round summary')}</span><h2 dir="ltr">${adQuiz.score} / ${total}</h2><p>${baT('הטעויות והרמזים נשמרו לצורך החזרה הבאה. אפשר לפתוח כרטיס ולבדוק מה הבדיל בין הסימונים.','Misses and hint use were saved for the next review. Open a card to examine the distinguishing landmarks.')}</p>${adQuiz.questions.map(x=>`<details class="ba-refs"><summary>${x.choices[x.answer]===x.code?'✓':'↻'} <b dir="ltr">${x.code}</b>${x.hinted?' · '+baT('עם רמז','with hint'):''}</summary><p>${baEsc(baT(AS.points[x.code].focus.he,AS.points[x.code].focus.en))}</p><button class="chip" data-open="point:${x.code}">${baT('לכרטיס הנקודה','Point card')}</button></details>`).join('')}<button class="btn" data-ad-quiz-restart>${baT('סבב חדש','New round')}</button></section>`;return;}
 asSaveSession();const answered=q.answer!==null,correct=q.choices[q.answer]===q.code,n=AS.points[q.code];
 el.innerHTML=asQuizToolbar()+`<div class="ad-quiz"><div class="ad-quiz-top"><span class="ba-tag">${baT('זיהוי חזותי','Visual identification')} · <b dir="ltr">${adQuiz.index+1} / ${total}</b></span><span>${adQuiz.score} ${baT('נכונות','correct')}</span></div><p class="ba-fine">${baT('בסבב הזה: ','This round: ')}${adQuiz.reviewCount} ${baT('נקודות לחזרה; היתר להרחבת התרגול.','review points; the rest broaden practice.')}</p><h2>${baT('איזה סימון מתאים ל־','Which marker is ')}<b dir="ltr">${q.code}</b>?</h2><p>${baEsc(adViewTitle(q.view))} · ${baT('בחרו אות בתרשים או בכפתורים.','Select a letter on the chart or below.')}</p>${adDiagram(q.view,{codes:q.choices,answers:answered?null:q.choices.map((_,i)=>String.fromCharCode(65+i)),selected:answered?q.code:'',labels:answered,interactive:!answered})}<div class="ad-answers" style="grid-template-columns:repeat(${q.choices.length},minmax(0,1fr))">${q.choices.map((c,i)=>`<button class="btn ghost ${answered&&c===q.code?'ad-correct':''} ${answered&&q.answer===i&&c!==q.code?'ad-incorrect':''}" data-ad-answer="${i}" ${answered?'disabled':''}>${String.fromCharCode(65+i)}${answered?' · '+c:''}</button>`).join('')}</div><div id="ad-feedback" role="status" aria-live="polite">${answered?`<h3>${correct?baT(q.hinted?'נכון, בעזרת רמז':'נכון',q.hinted?'Correct, with a hint':'Correct'):baT('נחזור על המיקום','Review the location')}</h3><p>${baEsc(asPrimaryText(q.code))}</p><p>${baEsc(baT(n.focus.he,n.focus.en))}</p>${adLandmarks(q.code)}<button class="btn" data-ad-quiz-next>${baT(adQuiz.index===total-1?'לתוצאות':'לשאלה הבאה',adQuiz.index===total-1?'Results':'Next question')}</button>`:''}</div>${!answered?`<details class="ba-refs" id="as-quiz-hint"><summary>${baT('רמז: תיאור המיקום','Hint: location description')}</summary><p>${baEsc(asPrimaryText(q.code))}</p></details>`:''}</div>`;
 const hint=$('#as-quiz-hint');if(hint&&!answered)hint.addEventListener('toggle',()=>{if(hint.open&&q.answer===null){q.hinted=true;asSaveSession();}});
};
adQuizAnswer=function(i){const q=adQuiz?.questions[adQuiz.index];if(!q||q.answer!==null||!Number.isInteger(i)||i<0||i>=q.choices.length)return;q.answer=i;if(q.choices[i]===q.code)adQuiz.score++;asRecordAnswer(q);asSaveSession();adQuizRender();$('#ad-feedback').scrollIntoView({block:'nearest',behavior:'smooth'});$('[data-ad-quiz-next]')?.focus({preventScroll:true});};
baValidateBackup=function(d){const safe=asOldBackup(d);safe.learningProgress=asValidateProgress(d.learningProgress);safe.visualSession=asValidateSession(d.visualSession);return safe;};
document.addEventListener('click',e=>{const b=e.target.closest('[data-as-landmark],[data-as-clear-landmark],[data-as-variant],[data-as-mode]');if(!b)return;
 if(b.hasAttribute('data-as-landmark')){const [c,i]=b.dataset.asLandmark.split('|');asHighlight(c,+i);}
 if(b.hasAttribute('data-as-clear-landmark')){asLandmark=-1;asRefreshChart();}
 if(b.hasAttribute('data-as-variant')){const mode=b.dataset.asVariant;if(['primary','alternate','both'].includes(mode)){asVariant=mode;asLandmark=-1;asRefreshChart();$('#ad-point-chart [data-as-variant="'+mode+'"]').focus();}}
 if(b.hasAttribute('data-as-mode')){asMode=b.dataset.asMode==='review'?'review':'mixed';adQuiz=adQuizBuild();asSaveSession();adQuizRender();}
});
