'use strict';
BA_SOURCES.appendicular=['NCI / SEER · Appendicular skeleton','https://training.seer.cancer.gov/anatomy/skeletal/divisions/appendicular.html'];
BA_SOURCES.fibularis=['Olewnik et al. · Fibularis brevis attachment, 2020','https://pubmed.ncbi.nlm.nih.gov/31031151/'];
const AN_PATHS=[
 {id:'hand-foundation',region:'hand',level:1,he:'כף היד · מבטים ומפרקים',en:'Hand · views and joints',steps:[
  ['LI 4','LU 10','מסרק ראשון ושני','First and second metacarpals','זהו את האגודל, החליפו בין המבטים ובדקו לאיזו עצם מתייחס כל תיאור.','Identify the thumb, compare views, and find the bone named by each description.'],
  ['SI 2','SI 3','שני צדי מפרק','Two sides of a joint','השוו דיסטלי ופרוקסימלי ביחס למפרק המסרק־גליל החמישי.','Compare distal and proximal relative to the fifth metacarpophalangeal joint.'],
  ['PC 7','HT 7','קריאת קפל שורש כף היד','Reading the wrist crease','חפשו את הקפל ואת הגיד הייחודי לכל תיאור; אותו גובה אינו אותו מיקום.','Find the crease and each description’s tendon; the same level is not the same location.']]},
 {id:'hand-comparison',region:'hand',level:2,he:'כף היד · ציפורניים וחלופות',en:'Hand · nails and alternatives',steps:[
  ['HT 9','SI 1','רדיאלי מול אולנרי','Radial versus ulnar','התחילו באותה ציפורן זרת ובדקו באיזה צד של בסיס הציפורן נמצא כל סימון.','Start at the same little-finger nail and compare the two sides of its proximal border.'],
  ['LU 11','TE 1','אותה הגדרת פינה, אצבע אחרת','Corner definitions across digits','זהו קודם את האצבע, אחר כך את בסיס הציפורן ואת הצד המתואר.','Identify the digit first, then the nail’s proximal border and the named side.'],
  ['PC 8','PC 9','ראשי וחלופי','Primary and alternative','פתחו כל כרטיס והשוו את חלופות המקור. שימו לב אם החלופה משנה מרווח או גם מבט.','Open each card and compare source alternatives. Note whether the alternative changes an interspace or also the view.']]},
 {id:'ankle-foundation',region:'ankle',level:1,he:'קרסול וכף רגל · ציוני דרך',en:'Ankle and foot · landmarks',steps:[
  ['KI 3','BL 60','פנימי וחיצוני','Medial and lateral','השוו את היחס לפטישון ולגיד אכילס בשני צדי הקרסול.','Compare malleolus and Achilles references on both sides of the ankle.'],
  ['KI 2','SP 5','עצם הסירה והפטישון','Navicular and malleolus','הדגישו את עצם הסירה ואת הפטישון. הבחינו בין קדימה, מטה והמרווח שביניהם.','Highlight navicular and malleolus; distinguish anterior, inferior and the interval between landmarks.'],
  ['SP 2','SP 3','המפרק הראשון בכף הרגל','The first foot joint','בדקו מאיזה צד של מפרק המסרק־גליל הראשון מתואר כל מיקום.','Check the named side of the first metatarsophalangeal joint for each location.']]},
 {id:'ankle-comparison',region:'ankle',level:2,he:'קרסול וכף רגל · יחסים סמוכים',en:'Ankle and foot · nearby relationships',steps:[
  ['BL 63','BL 64','קובייה ובסיס המסרק','Cuboid and metatarsal base','עקבו אחר המעבר מתחת לקובייה אל דיסטלית לבסיס המסרק החמישי.','Follow the change from inferior to the cuboid to distal to the fifth metatarsal base.'],
  ['KI 5','KI 6','מתחת לקרסול, אך לא אותו עוגן','Below the ankle, different anchors','השוו את עוגן המדידה ואת היחס לפטישון; הימנעו מזיהוי לפי גובה בלבד.','Compare the measuring anchor and malleolar relationship; avoid using height alone.'],
  ['BL 65','BL 66','לפני ואחרי המפרק החמישי','Across the fifth joint','זהו את המפרק ואז את הצד הפרוקסימלי והדיסטלי בתיאור.','Identify the joint, then proximal and distal in the descriptions.']]},
 {id:'face-foundation',region:'face',level:1,he:'פנים · עין, אף ופה',en:'Face · eye, nose and mouth',steps:[
  ['ST 1','ST 2','שפה גרמית ונקב','Bony rim and foramen','השוו בין אזור שמתחת לגלגל העין לבין הנקב התת־ארובתי.','Compare the region below the eyeball with the infraorbital foramen.'],
  ['ST 3','ST 4','שני גבהים בפנים','Two facial levels','השתמשו בכנף האף ובזווית הפה כדי להבחין בין הגבהים.','Use the nasal ala and mouth corner to distinguish the levels.'],
  ['LI 19','LI 20','חריץ השפה וקפל האף','Philtrum and nasal fold','הדגישו כל ציון דרך והשוו את ההיסט מקו האמצע.','Highlight each landmark and compare its midline offset.']]},
 {id:'face-comparison',region:'face',level:2,he:'פנים וצוואר · חלופות ועומק',en:'Face and neck · alternatives and depth',steps:[
  ['LI 19','GV 26','אותו חריץ, יחס שונה','Same groove, different relation','השוו ראשי וחלופי בשני הכרטיסים; הבדילו בין קו אמצע להיסט צדדי.','Compare primary and alternative in both cards; distinguish the midline from lateral offset.'],
  ['ST 9','LI 18','אותו גובה, צד שונה של שריר','Same level, different muscle border','הדגישו את השריר הסטרנוקליידומסטואידי ואת סחוס התריס.','Highlight sternocleidomastoid and thyroid cartilage.'],
  ['ST 10','LI 17','גובה הקריקואיד','Cricoid level','השוו את הגובה עם השלב הקודם ואת היחס לשולי השריר.','Compare the level with the preceding step and the relationship to the muscle borders.']]},
 {id:'pelvis-foundation',region:'pelvis',level:1,he:'אגן · מסגרת הייחוס',en:'Pelvis · reference framework',steps:[
  ['GB 29','GB 30','שלושה ציוני דרך','Three landmarks','הדגישו את קוץ הכסל, התל הגדול ופתח העצה; פתח העצה מוצג כהיטל ייחוס אחורי.','Highlight ASIS, greater trochanter and sacral hiatus; the hiatus is shown as a projected posterior reference.'],
  ['BL 31','BL 32','סדר פתחי העצה','Sacral foramen sequence','בדקו את מספר הפתח האחורי ואת סדר הסימונים, ולא את מספר הנקודה בלבד.','Check the posterior foramen number and marker order, not the point number alone.'],
  ['CV 2','CV 3','מאחה הערווה וקו האמצע','Pubic symphysis and midline','חפשו את הגבול העליון של מאחה הערווה ואת המדידה שמתחילה ממנו.','Find the superior pubic symphysis border and the measurement anchored to it.']]},
 {id:'pelvis-comparison',region:'pelvis',level:2,he:'אגן · קווים ומדידות',en:'Pelvis · lines and measures',steps:[
  ['GB 29','GB 30','אמצע קו מול חלוקת שלישים','Midpoint versus thirds','הציגו את חלופות GB 30. בדקו בכל פעם את שני קצות הקו ואת החלק היחסי.','Show GB 30 alternatives. Check both endpoints and the stated fraction each time.'],
  ['BL 33','BL 34','פתח שלישי ורביעי','Third and fourth foramina','זהו את העצה ובדקו שהמספר מתייחס לפתח האחורי ולא לחוליה מותנית.','Identify the sacrum; confirm the number refers to a posterior foramen, not a lumbar vertebra.'],
  ['ST 30','SP 12','אותו אזור, מרחק צדדי אחר','Same region, different lateral offset','השוו את קו האמצע ואת המרחק הצדדי, יחד עם ציוני הדרך המופיעים בכל רשומה.','Compare the midline and lateral offset together with each record’s landmarks.']]}
];
const anCourse=id=>AN_PATHS.find(p=>p.id===id);
const anCodes=p=>[...new Set(p.steps.flatMap(s=>s.slice(0,2)))];
let anCourseRegion='all',anCourseLevel=0,anQuizPathId=null,anZoom='auto',anChartContext=false;
function anEmptyCourses(){return {version:1,active:null,completed:{},results:{}};}
function anValidateCourses(v){
 if(v==null)return anEmptyCourses();if(typeof v!=='object'||Array.isArray(v)||v.version!==1||!v.completed||typeof v.completed!=='object'||Array.isArray(v.completed)||!v.results||typeof v.results!=='object'||Array.isArray(v.results)||v.active!==null&&!anCourse(v.active))throw Error('Invalid course progress');
 const clean=anEmptyCourses();clean.active=v.active;
 for(const [id,steps]of Object.entries(v.completed)){const p=anCourse(id);if(!p||!Array.isArray(steps)||steps.some(n=>!Number.isInteger(n)||n<0||n>=p.steps.length)||new Set(steps).size!==steps.length)throw Error('Invalid course step');clean.completed[id]=[...steps].sort();}
 for(const [id,r]of Object.entries(v.results)){if(!anCourse(id)||!r||typeof r.id!=='string'||r.id.length>80||!Number.isInteger(r.score)||!Number.isInteger(r.total)||r.total<1||r.total>8||r.score<0||r.score>r.total||!asValidDate(r.date))throw Error('Invalid course result');clean.results[id]={id:r.id,score:r.score,total:r.total,date:r.date};}return clean;
}
function anProgress(){try{return anValidateCourses(store.get('courseProgress',null));}catch{return anEmptyCourses();}}
function anSetStep(id,i,done){const p=anCourse(id);if(!p||!Number.isInteger(i)||i<0||i>=p.steps.length)return;const v=anProgress(),set=new Set(v.completed[id]||[]);done?set.add(i):set.delete(i);v.completed[id]=[...set].sort();store.set('courseProgress',v);}
function anPathsRender(){
 const state=anProgress(),p=anCourse(state.active),el=$('#learnBody');
 if(p){const done=state.completed[p.id]||[],r=state.results[p.id];el.innerHTML=`<button class="chip" data-an-path="">${baT('כל מסלולי הלימוד','All learning paths')}</button><section class="card ba-pad"><span class="ba-tag">${baT(p.level===1?'יסודות':'השוואות',p.level===1?'Foundation':'Comparison')}</span><h2>${baEsc(baT(p.he,p.en))}</h2><p>${baT('פתחו את הכרטיסים, הדגישו ציוני דרך והשוו. סמנו שלב לאחר שקראתם והבנתם את ההבדל. הסימון הוא מעקב אישי.','Open cards, highlight landmarks and compare. Mark a step after reading and understanding the distinction. Checkmarks are personal progress tracking.')}</p><p class="an-path-status" aria-live="polite">${done.length} / ${p.steps.length} ${baT('שלבים נקראו','steps read')}</p>${p.steps.map((s,i)=>`<article class="an-step"><h3>${i+1}. ${baEsc(baT(s[2],s[3]))}</h3><p>${baEsc(baT(s[4],s[5]))}</p><div class="ad-tools"><button class="chip" data-open="point:${s[0]}" dir="ltr">${s[0]}</button><button class="chip" data-open="point:${s[1]}" dir="ltr">${s[1]}</button><button class="chip" data-ad-pair="${s[0]}|${s[1]}">${baT('השוואה','Compare')}</button></div><label><input type="checkbox" data-an-step="${p.id}|${i}" ${done.includes(i)?'checked':''}>${baT('קראתי והבנתי את ההבדל','I read and understood the distinction')}</label></article>`).join('')}<div class="an-path-banner"><h3>${baT('תרגול מסכם לאזור הזה','Practice this path')}</h3><p>${baT('השאלות נבחרות מתוך נקודות המסלול; אפשרויות ההשוואה מגיעות מאותו מבט. אפשר לחזור לכאן גם לאחר תרגול חלקי.','Questions use points from this path; distractors come from the same view. You can return here during a partial round.')}</p><button class="btn" data-an-quiz="${p.id}">${baT('התחלת תרגול ממוקד','Start focused practice')}</button>${r?`<p>${baT('תוצאה אחרונה','Last result')}: <b dir="ltr">${r.score} / ${r.total}</b></p>`:''}</div></section>`;return;}
 const regionNames=[['all','כל האזורים','All regions'],['hand','כף היד','Hand'],['ankle','קרסול וכף רגל','Ankle and foot'],['face','פנים וצוואר','Face and neck'],['pelvis','אגן','Pelvis']];
 const paths=AN_PATHS.filter(x=>(anCourseRegion==='all'||x.region===anCourseRegion)&&(!anCourseLevel||x.level===anCourseLevel));
 el.innerHTML=`<section class="card ba-pad"><span class="ba-tag">${baT('ללמוד בסדר ברור','Learn in sequence')}</span><h2>${baT('מסלולי לימוד לפי אזור ורמה','Learning paths by region and level')}</h2><p>${baT('יסודות: מבט, ציון דרך וכיוון. השוואות: נקודות סמוכות, חלופות ומדידות. בכל מסלול שלושה שלבים ותרגול מסכם.','Foundation: view, landmark and direction. Comparison: nearby points, alternatives and measures. Each path has three steps and focused practice.')}</p><div class="an-filter" role="group" aria-label="${baT('אזור','Region')}">${regionNames.map(([k,h,e])=>`<button class="chip" data-an-region="${k}" aria-pressed="${k===anCourseRegion}">${baT(h,e)}</button>`).join('')}</div><div class="an-filter" role="group" aria-label="${baT('רמה','Level')}">${[[0,'כל הרמות','All levels'],[1,'יסודות','Foundation'],[2,'השוואות','Comparison']].map(([k,h,e])=>`<button class="chip" data-an-level="${k}" aria-pressed="${k===anCourseLevel}">${baT(h,e)}</button>`).join('')}</div></section><div class="an-path-grid">${paths.map(p=>{const n=(state.completed[p.id]||[]).length;return `<article class="an-path-card"><span class="ba-tag">${baT(p.level===1?'יסודות':'השוואות',p.level===1?'Foundation':'Comparison')}</span><h3>${baEsc(baT(p.he,p.en))}</h3><p>${p.steps.map(s=>baEsc(baT(s[2],s[3]))).join(' · ')}</p><progress value="${n}" max="3" aria-label="${baT('התקדמות','Progress')}"></progress><p>${n} / 3 ${baT('שלבים נקראו','steps read')}</p><button class="btn ghost" data-an-path="${p.id}">${baT(n?'המשך למידה':'פתיחת המסלול',n?'Continue learning':'Open path')}</button></article>`;}).join('')}</div>`;
}
const anOldLearn=learnScreen,anOldBackup=baValidateBackup,anOldSession=asValidateSession,anOldBuild=adQuizBuild,anOldQuizRender=adQuizRender,anOldStudy=adStudy,anOldReview=adReview,anOldChart=adPointChart,anOldDiagram=adDiagram,anOldOpen=openItem;
learnScreen=function(){anOldLearn();$('.ba-learning-tabs').insertAdjacentHTML('beforeend',`<button class="chip ${baLearnTab==='paths'?'active':''}" data-ba-tab="paths" aria-pressed="${baLearnTab==='paths'}">${baT('מסלולי לימוד','Learning paths')}</button>`);if(baLearnTab==='paths')anPathsRender();};
baValidateBackup=function(v){const safe=anOldBackup(v);safe.courseProgress=anValidateCourses(v.courseProgress);return safe;};
asValidateSession=function(v){const q=anOldSession(v);if(!q)return null;if(v.pathId!=null){const p=anCourse(v.pathId);if(!p||q.questions.some(x=>!anCodes(p).includes(x.code)))return null;q.pathId=p.id;}else q.pathId=null;return q;};
adQuizBuild=function(){const p=anCourse(anQuizPathId);if(!p)return {...anOldBuild(),pathId:null};const questions=baShuffle(anCodes(p)).map(c=>({code:c,view:AD.points[c].view,choices:asCandidates(c),answer:null,hinted:false})).filter(q=>q.choices).map(q=>({...q,choices:baShuffle(q.choices)}));return {version:'3.3.0',id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10),mode:'mixed',pathId:p.id,questions,index:0,score:0,saved:false,reviewCount:questions.filter(q=>asNeedsReview(asProgress().points[q.code])).length};};
adQuizRender=function(){anOldQuizRender();const p=anCourse(adQuiz?.pathId);anQuizPathId=p?.id||null;if(p){$('#learnBody').insertAdjacentHTML('afterbegin',`<div class="an-path-banner"><b>${baEsc(baT(p.he,p.en))}</b><button class="chip" data-an-return="${p.id}">${baT('חזרה למסלול','Back to path')}</button><button class="chip" data-an-general>${baT('תרגול מכל האטלס','Practice the whole atlas')}</button></div>`);if(adQuiz.saved){const v=anProgress();if(v.results[p.id]?.id!==adQuiz.id){v.results[p.id]={id:adQuiz.id,score:adQuiz.score,total:adQuiz.questions.length,date:new Date().toISOString()};store.set('courseProgress',v);}}}};
const AN_ZOOMS={handBack:[['fingers','אצבעות וציפורניים','Fingers and nails',[125,70,640,520]],['wrist','מסרקים ושורש כף היד','Metacarpals and wrist',[245,425,505,520]]],handPalm:[['fingers','אצבעות','Fingers',[220,70,665,520]],['wrist','כף היד ושורש כף היד','Palm and wrist',[240,420,540,520]]],face:[['upper','עיניים ואף','Eyes and nose',[280,320,440,330]],['neck','צוואר','Neck',[240,680,520,280]]],footMedial:[['ankle','קרסול ועקב','Ankle and heel',[140,300,420,500]],['forefoot','קדמת כף הרגל','Forefoot',[425,520,480,265]]],footLateral:[['ankle','קרסול ועקב','Ankle and heel',[140,300,420,500]],['forefoot','קדמת כף הרגל','Forefoot',[410,505,495,280]]],hip:[['hip','מסגרת האגן','Pelvic framework',[205,140,610,585]]]};
function anOrientation(v){return baT(v.startsWith('hand')?'כף יד ימין: הצד הרדיאלי הוא צד האגודל; בכף ובגב הכיוונים מתהפכים על המסך.':v.startsWith('foot')?'מבט מן הצד: העקב משמאל והאצבעות מימין. המבנים העמוקים מוצגים כהיטל.':v==='face'?'מבט קדמי: הצד הימני של האדם מופיע משמאל לצופה. שכבת העצמות היא היטל ייחוס.':'סכמת אגן: קוץ הכסל קדמי, פתח העצה אחורי. שילוב ציוני הדרך הוא היטל לימודי.',v.startsWith('hand')?'Right hand: radial means thumb side; palmar and dorsal views reverse screen orientation.':v.startsWith('foot')?'Side view: heel at left, toes at right. Deep structures are shown as projections.':v==='face'?'Anterior view: the person’s right appears on the viewer’s left. Bone layer is a reference projection.':'Pelvic schematic: ASIS is anterior and the sacral hiatus posterior. Combined landmarks form a teaching projection.');}
adDiagram=function(view,opts={}){const zoom=AN_ZOOMS[view]?.find(z=>z[0]===anZoom);if(anChartContext&&zoom&&!opts.frame)opts={...opts,frame:zoom[3]};return anOldDiagram(view,opts);};
adPointChart=function(){const v=AD.points[adCurrent]?.view;anChartContext=true;let html;try{html=anOldChart();}finally{anChartContext=false;}if(!AN_VIEWS.includes(v))return html;
 const controls=`<section class="an-controls"><h4>${baT('שכבות ומבטים','Layers and views')}</h4><div class="ad-tools">${[['combined','משולב','Combined'],['bones','עצמות ייחוס','Bone references'],['soft','רקמות רכות','Soft structures']].map(([k,h,e])=>`<button class="chip" data-an-layer="${k}" aria-pressed="${anLayer===k}">${baT(h,e)}</button>`).join('')}</div><div class="an-swatches"><span>${baT('עצם','Bone')}</span><span>${baT('שריר','Muscle')}</span><span>${baT('גיד ורקמת חיבור','Tendon / connective tissue')}</span></div><div class="ad-tools"><button class="chip" data-an-zoom="auto" aria-pressed="${anZoom==='auto'}">${baT('לפי הנקודה','Follow point')}</button>${AN_ZOOMS[v].map(([k,h,e])=>`<button class="chip" data-an-zoom="${k}" aria-pressed="${anZoom===k}">${baT(h,e)}</button>`).join('')}</div><p class="an-orientation">${anOrientation(v)}</p><p class="an-orientation">${baT('השכבות מדגישות מבנים נבחרים ואינן חתך אנטומי מלא. מרחקים בסכמה אינם מדידה על הגוף.','Layers emphasize selected structures, not a complete anatomical section. Schematic distances are not measurements on a person.')}</p></section>`;
 return controls+html;
};
openItem=function(key){if(key.startsWith('point:'))anZoom='auto';anOldOpen(key);};
adStudy=function(c){const html=anOldStudy(c),state=anProgress(),p=anCourse(state.active);return html+(p&&anCodes(p).includes(c)?`<button class="chip" data-an-return="${p.id}">${baT('חזרה למסלול: ','Back to path: ')+baEsc(baT(p.he,p.en))}</button>`:'');};
adReview=function(c){const d=AD.points[c];return anOldReview(c)+(d.adjustment33?`<details class="ba-refs"><summary>${baT('התאמת התרשים במהדורה 3.3','Version 3.3 diagram alignment')}</summary><p>${baEsc(baT(d.adjustment33.he,d.adjustment33.en))}</p><p>${baT('התאמה עריכתית לתיאור שסופק, הממתינה לבדיקת איש מקצוע.','Editorial alignment to the supplied description, pending professional review.')}</p></details>`:'')+(d.sourceIssue33?`<details class="ba-refs"><summary>${baT('אי־התאמה בהערת המקור','Source-note inconsistency')}</summary><p>${baEsc(baT(d.sourceIssue33.he,d.sourceIssue33.en))}</p></details>`:'');};
document.addEventListener('change',e=>{const b=e.target.closest('[data-an-step]');if(b){const [id,i]=b.dataset.anStep.split('|');anSetStep(id,+i,b.checked);const status=$('.an-path-status');if(status)status.textContent=(anProgress().completed[id]||[]).length+' / 3 '+baT('שלבים נקראו','steps read');}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-an-path],[data-an-region],[data-an-level],[data-an-quiz],[data-an-return],[data-an-general],[data-an-layer],[data-an-zoom]');if(!b)return;
 if(b.hasAttribute('data-an-path')||b.hasAttribute('data-an-return')){const id=b.dataset.anPath??b.dataset.anReturn,state=anProgress();state.active=anCourse(id)?.id||null;store.set('courseProgress',state);closeSheet();baLearnTab='paths';route('learn');}
 if(b.hasAttribute('data-an-region')){anCourseRegion=b.dataset.anRegion;anPathsRender();}
 if(b.hasAttribute('data-an-level')){anCourseLevel=+b.dataset.anLevel;anPathsRender();}
 if(b.hasAttribute('data-an-quiz')){anQuizPathId=b.dataset.anQuiz;if(!anCourse(anQuizPathId))return;adQuiz=adQuizBuild();asSaveSession();baLearnTab='visual';route('learn');}
 if(b.hasAttribute('data-an-general')){anQuizPathId=null;adQuiz=adQuizBuild();asSaveSession();adQuizRender();}
 if(b.hasAttribute('data-an-layer')){const key=b.dataset.anLayer;if(['combined','bones','soft'].includes(key)){anLayer=key;asRefreshChart();$('#ad-point-chart [data-an-layer="'+key+'"]')?.focus({preventScroll:true});}}
 if(b.hasAttribute('data-an-zoom')){anZoom=b.dataset.anZoom;asRefreshChart();$('#ad-point-chart [data-an-zoom="'+anZoom+'"]')?.focus({preventScroll:true});}
});
// Capture mode and full-view controls before older delegated handlers re-render.
document.addEventListener('click',e=>{if(e.target.closest('[data-as-mode]'))anQuizPathId=null;if(e.target.closest('[data-ad-zoom],[data-as-landmark],[data-as-variant]'))anZoom='auto';},true);
const anOldAbout=aboutScreen;
aboutScreen=function(){anOldAbout();$('#view .screen').insertAdjacentHTML('beforeend',`<section class="card ba-pad"><h2>${baT('מה חדש ב־3.3?','What is new in 3.3?')}</h2><p>${baT('215 הסברים נוספים נערכו בעברית ובאנגלית. שישה מבטים הורחבו לשכבות עצמות ורקמות רכות, ונוספו שמונה מסלולי לימוד עם התקדמות שמורה.','215 more point explanations were edited in Hebrew and English. Six views gained bone and soft-structure layers, with eight learning paths and saved progress.')}</p><p>${baT('13 סימונים הותאמו לציוני הדרך בסכמה. זהו תיקון עריכתי, ולא אישור קליני. אי־התאמה בהערת המקור של SP 19 מתועדת ביומן הבדיקה.','13 markers were aligned with schematic landmarks. This is editorial correction, not clinical approval. A source-note inconsistency for SP 19 is documented in the review register.')}</p><p>${baT('בדיקות מהדורה: 22.09.2026. הסקירה המקצועית ובדיקת הטלפון הפיזי עדיין ממתינות.','Release checks: 22 September 2026. Professional review and physical-phone testing remain pending.')}</p></section>`);};
